'use client'

import { useState, useEffect } from 'react'
import { Search, TrendingUp, BarChart3, Copy, Target, Shield, ExternalLink, ChevronLeft, ChevronRight, Users, ShoppingCart } from 'lucide-react'
import { cn } from '@/lib/utils'
import { PageTransition } from '@/components/ui/page-transition'
import { useAuth } from '@/lib/auth-context'
import { useRouter } from 'next/navigation'
import { toast } from 'sonner'
import {
  Dialog,
  DialogContent,
} from '@/components/ui/dialog'

const categories = ['All', 'Gold', 'Forex', 'Crypto', 'Scalping', 'Mean Reversion', 'Breakout', 'Trend Following']

// Generate realistic equity curve points
function generateEquityCurve(seed: number, points: number = 40): number[] {
  const curve: number[] = [100]
  let val = 100
  for (let i = 1; i < points; i++) {
    const noise = Math.sin(seed * i * 0.7) * 2 + Math.cos(seed * i * 0.3) * 1.5
    val += noise * 0.4 + 0.3
    curve.push(val)
  }
  return curve
}

// Gradient backgrounds for strategy thumbnails
const gradients = [
  'from-violet-500/20 via-purple-500/10 to-fuchsia-500/5',
  'from-emerald-500/20 via-teal-500/10 to-cyan-500/5',
  'from-orange-500/20 via-amber-500/10 to-yellow-500/5',
  'from-blue-500/20 via-indigo-500/10 to-violet-500/5',
  'from-rose-500/20 via-pink-500/10 to-red-500/5',
  'from-cyan-500/20 via-sky-500/10 to-blue-500/5',
  'from-lime-500/20 via-green-500/10 to-emerald-500/5',
  'from-amber-500/20 via-orange-500/10 to-red-500/5',
  'from-fuchsia-500/20 via-pink-500/10 to-rose-500/5',
]

const mockStrategies = [
  {
    id: '1',
    name: 'Multi-Pair Mean Reversion Kalman v2',
    author: 'SIGX',
    isSigx: true,
    market: 'XAUUSD',
    tags: ['Gold', 'Mean Reversion', 'M15'],
    price: 'Free',
    priceCents: 0,
    platform: 'mql5',
    mqlCode: `//+------------------------------------------------------------------+\n//| Multi-Pair Mean Reversion Kalman v2.mq5\n//| Generated by SIGX\n//+------------------------------------------------------------------+\n#property copyright "SIGX"\n#include <Trade/Trade.mqh>\n\nCTrade trade;\n\ninput double RiskPercent = 1.0;\ninput int MagicNumber = 100001;\n\nint OnInit() {\n    trade.SetExpertMagicNumber(MagicNumber);\n    return INIT_SUCCEEDED;\n}\n\nvoid OnTick() {\n    // Strategy logic here\n}\n`,
    sharpe: 1.57,
    annualReturn: 11.09,
    totalReturn: 42.82,
    drawdown: -2.89,
    winRate: 58.3,
    copies: 128,
    description: 'VWAP and Bollinger Band mean reversion with Kalman filter smoothing on M15. This strategy identifies mean-reverting opportunities using advanced statistical methods and executes with tight risk management.',
    entryRules: ['Price touches lower/upper BB', 'Kalman filter divergence', 'Volume spike detected'],
    exitRules: ['VWAP mean return', 'Opposite BB touch', 'ATR trailing stop'],
    riskLogic: 'Risk 1.5% per trade with position scaling.',
    equityCurve: generateEquityCurve(1.2),
  },
  {
    id: '2',
    name: 'Gold Breakout Pro London Session',
    author: 'TraderX',
    isSigx: false,
    market: 'XAUUSD',
    tags: ['Gold', 'Breakout', 'M5'],
    price: '$19.99',
    priceCents: 1999,
    platform: 'mql5',
    mqlCode: `//+------------------------------------------------------------------+\n//| Gold Breakout Pro London Session.mq5\n//| Generated by SIGX\n//+------------------------------------------------------------------+\n#property copyright "SIGX"\n#include <Trade/Trade.mqh>\n\nCTrade trade;\n\ninput double RiskPercent = 1.0;\ninput int MagicNumber = 200001;\n\nint OnInit() {\n    trade.SetExpertMagicNumber(MagicNumber);\n    return INIT_SUCCEEDED;\n}\n\nvoid OnTick() {\n    // Strategy logic here\n}\n`,
    sharpe: 2.34,
    annualReturn: 22.6,
    totalReturn: 45.20,
    drawdown: -4.10,
    winRate: 56.1,
    copies: 95,
    description: 'Breakout strategy using London session liquidity sweeps with FVG confirmation. Targets the high-volume London open for clean breakout entries with institutional order flow.',
    entryRules: ['London session open breakout', 'FVG confirmation on M5', 'RSI above 55 for longs'],
    exitRules: ['2x ATR take profit', '1.5x ATR stop loss', 'Trailing after 1 ATR'],
    riskLogic: 'Risk 1% per trade, max 2 positions, daily loss cap 3%.',
    equityCurve: generateEquityCurve(2.5),
  },
  {
    id: '3',
    name: 'EUR Momentum Alpha EMA Cross',
    author: 'SIGX',
    isSigx: true,
    market: 'EURUSD',
    tags: ['Forex', 'Trend Following', 'H1'],
    price: 'Free',
    priceCents: 0,
    platform: 'mql5',
    mqlCode: `//+------------------------------------------------------------------+\n//| EUR Momentum Alpha EMA Cross.mq5\n//| Generated by SIGX\n//+------------------------------------------------------------------+\n#property copyright "SIGX"\n#include <Trade/Trade.mqh>\n\nCTrade trade;\n\ninput double RiskPercent = 1.0;\ninput int MagicNumber = 300001;\n\nint OnInit() {\n    trade.SetExpertMagicNumber(MagicNumber);\n    return INIT_SUCCEEDED;\n}\n\nvoid OnTick() {\n    // Strategy logic here\n}\n`,
    sharpe: 2.12,
    annualReturn: 19.35,
    totalReturn: 38.70,
    drawdown: -5.30,
    winRate: 54.1,
    copies: 67,
    description: 'EMA momentum with RSI divergence entries on H1 timeframe. Captures intermediate trends in the EUR/USD pair using classic momentum indicators combined with divergence analysis.',
    entryRules: ['EMA 20/50 crossover', 'RSI divergence confirmation', 'Volume above average'],
    exitRules: ['EMA reverse crossover', 'RSI overbought/oversold exit', 'Time-based close at 22:00'],
    riskLogic: 'Risk 0.5% per trade, scale in on confirmation.',
    equityCurve: generateEquityCurve(3.1),
  },
  {
    id: '4',
    name: 'Cable Scalper v3 LDN/NY Overlap',
    author: 'FXPro',
    isSigx: false,
    market: 'GBPUSD',
    tags: ['Forex', 'Scalping', 'M1'],
    price: '$9.99',
    priceCents: 999,
    platform: 'mql4',
    mqlCode: `//+------------------------------------------------------------------+\n//| Cable Scalper v3 LDN/NY Overlap.mq4\n//| Generated by SIGX\n//+------------------------------------------------------------------+\n#property copyright "SIGX"\n\nextern double RiskPercent = 1.0;\nextern int MagicNumber = 400001;\n\nint init() {\n    return(0);\n}\n\nint start() {\n    // Strategy logic here\n    return(0);\n}\n`,
    sharpe: 1.98,
    annualReturn: 16.05,
    totalReturn: 32.10,
    drawdown: -6.20,
    winRate: 62.7,
    copies: 54,
    description: 'Fast scalping during London/NY overlap with tight risk management. Exploits the high-liquidity period where both London and New York sessions overlap for quick entries and exits.',
    entryRules: ['London/NY overlap window', 'Order block rejection', 'Spread below 2 pips'],
    exitRules: ['5 pip take profit', '3 pip stop loss', 'Close after 15 minutes'],
    riskLogic: 'Max 3 trades per session, 0.25% risk per trade.',
    equityCurve: generateEquityCurve(4.7),
  },
  {
    id: '5',
    name: 'BTC Trend Following Adaptive',
    author: 'CryptoAlgo',
    isSigx: false,
    market: 'BTCUSD',
    tags: ['Crypto', 'Trend Following', 'H4'],
    price: '$35',
    priceCents: 3500,
    platform: 'mql5',
    mqlCode: `//+------------------------------------------------------------------+\n//| BTC Trend Following Adaptive.mq5\n//| Generated by SIGX\n//+------------------------------------------------------------------+\n#property copyright "SIGX"\n#include <Trade/Trade.mqh>\n\nCTrade trade;\n\ninput double RiskPercent = 1.0;\ninput int MagicNumber = 500001;\n\nint OnInit() {\n    trade.SetExpertMagicNumber(MagicNumber);\n    return INIT_SUCCEEDED;\n}\n\nvoid OnTick() {\n    // Strategy logic here\n}\n`,
    sharpe: 1.45,
    annualReturn: 28.40,
    totalReturn: 56.80,
    drawdown: -12.30,
    winRate: 47.2,
    copies: 43,
    description: 'Adaptive trend following with dynamic position sizing for Bitcoin. Uses the Supertrend indicator with ADX confirmation and adjusts position size based on current volatility regime.',
    entryRules: ['ADX above 25', 'Supertrend flip confirmation', 'Funding rate neutral'],
    exitRules: ['Supertrend reverse', 'ATR trailing x2', 'Max hold 72h'],
    riskLogic: 'Risk 2% per trade, reduce to 1% in high volatility.',
    equityCurve: generateEquityCurve(5.3),
  },
  {
    id: '6',
    name: 'Silver Bullet ICT NY Killzone',
    author: 'SMCTrader',
    isSigx: false,
    market: 'XAUUSD',
    tags: ['Gold', 'Breakout', 'M15'],
    price: 'Free',
    priceCents: 0,
    platform: 'mql5',
    mqlCode: `//+------------------------------------------------------------------+\n//| Silver Bullet ICT NY Killzone.mq5\n//| Generated by SIGX\n//+------------------------------------------------------------------+\n#property copyright "SIGX"\n#include <Trade/Trade.mqh>\n\nCTrade trade;\n\ninput double RiskPercent = 1.0;\ninput int MagicNumber = 600001;\n\nint OnInit() {\n    trade.SetExpertMagicNumber(MagicNumber);\n    return INIT_SUCCEEDED;\n}\n\nvoid OnTick() {\n    // Strategy logic here\n}\n`,
    sharpe: 1.68,
    annualReturn: 11.15,
    totalReturn: 22.30,
    drawdown: -8.40,
    winRate: 48.6,
    copies: 89,
    description: 'ICT Silver Bullet model targeting the 10-11am NY killzone. Uses Smart Money Concepts including fair value gaps and displacement to identify institutional order flow entries.',
    entryRules: ['10-11am NY killzone', 'Fair value gap entry', 'Displacement confirmation'],
    exitRules: ['Internal range liquidity', 'Opposing order block', 'Session close'],
    riskLogic: 'Risk 2% per trade with single daily exposure.',
    equityCurve: generateEquityCurve(6.8),
  },
  {
    id: '7',
    name: 'NASDAQ Overnight Gap Strategy',
    author: 'SIGX',
    isSigx: true,
    market: 'NAS100',
    tags: ['Breakout', 'Trend Following'],
    price: '$19.99',
    priceCents: 1999,
    platform: 'mql5',
    mqlCode: `//+------------------------------------------------------------------+\n//| NASDAQ Overnight Gap Strategy.mq5\n//| Generated by SIGX\n//+------------------------------------------------------------------+\n#property copyright "SIGX"\n#include <Trade/Trade.mqh>\n\nCTrade trade;\n\ninput double RiskPercent = 1.0;\ninput int MagicNumber = 700001;\n\nint OnInit() {\n    trade.SetExpertMagicNumber(MagicNumber);\n    return INIT_SUCCEEDED;\n}\n\nvoid OnTick() {\n    // Strategy logic here\n}\n`,
    sharpe: 1.82,
    annualReturn: 24.5,
    totalReturn: 49.0,
    drawdown: -7.1,
    winRate: 52.4,
    copies: 31,
    description: 'Exploits overnight gap fills in NASDAQ 100. Identifies statistically significant gaps at market open and trades the mean-reverting tendency during the first hour of US session.',
    entryRules: ['Gap > 0.3% at open', 'Volume confirmation within 5 min', 'No major news within 30 min'],
    exitRules: ['Gap fill target', '50% gap retrace stop', 'Time exit at 11:00 EST'],
    riskLogic: 'Risk 1% per trade, max 1 trade per day.',
    equityCurve: generateEquityCurve(7.2),
  },
  {
    id: '8',
    name: 'JPY Carry Trade Momentum',
    author: 'MacroAlpha',
    isSigx: false,
    market: 'USDJPY',
    tags: ['Forex', 'Trend Following', 'D1'],
    price: 'Free',
    priceCents: 0,
    platform: 'mql4',
    mqlCode: `//+------------------------------------------------------------------+\n//| JPY Carry Trade Momentum.mq4\n//| Generated by SIGX\n//+------------------------------------------------------------------+\n#property copyright "SIGX"\n\nextern double RiskPercent = 1.0;\nextern int MagicNumber = 800001;\n\nint init() {\n    return(0);\n}\n\nint start() {\n    // Strategy logic here\n    return(0);\n}\n`,
    sharpe: 1.35,
    annualReturn: 14.2,
    totalReturn: 28.4,
    drawdown: -9.8,
    winRate: 45.0,
    copies: 22,
    description: 'Captures carry trade momentum in USD/JPY. Combines interest rate differential analysis with technical momentum indicators for swing trading on the daily timeframe.',
    entryRules: ['Positive carry direction', 'Price above 50 SMA', 'MACD histogram rising'],
    exitRules: ['MACD crossover exit', 'ATR x3 trailing stop', 'Carry reversal signal'],
    riskLogic: 'Risk 1% per trade, hold max 10 days.',
    equityCurve: generateEquityCurve(8.1),
  },
  {
    id: '9',
    name: 'ETH DeFi Volatility Capture',
    author: 'DeFiQuant',
    isSigx: false,
    market: 'ETHUSD',
    tags: ['Crypto', 'Mean Reversion', 'H1'],
    price: '$39.99',
    priceCents: 3999,
    platform: 'mql5',
    mqlCode: `//+------------------------------------------------------------------+\n//| ETH DeFi Volatility Capture.mq5\n//| Generated by SIGX\n//+------------------------------------------------------------------+\n#property copyright "SIGX"\n#include <Trade/Trade.mqh>\n\nCTrade trade;\n\ninput double RiskPercent = 1.0;\ninput int MagicNumber = 900001;\n\nint OnInit() {\n    trade.SetExpertMagicNumber(MagicNumber);\n    return INIT_SUCCEEDED;\n}\n\nvoid OnTick() {\n    // Strategy logic here\n}\n`,
    sharpe: 1.91,
    annualReturn: 35.6,
    totalReturn: 71.2,
    drawdown: -15.5,
    winRate: 51.3,
    copies: 18,
    description: 'Captures volatility spikes in Ethereum during DeFi events. Uses on-chain metrics combined with technical analysis to identify mean-reverting opportunities after large moves.',
    entryRules: ['Volatility spike > 2 std dev', 'RSI extreme (below 25 or above 75)', 'Volume > 2x average'],
    exitRules: ['Mean reversion to VWAP', 'Opposite extreme reached', '4h time stop'],
    riskLogic: 'Risk 1.5% per trade, reduce size in extreme volatility.',
    equityCurve: generateEquityCurve(9.4),
  },
]

type MockStrategy = (typeof mockStrategies)[0]

function EquityCurveSVG({ data, id }: { data: number[]; id: string }) {
  const width = 320
  const height = 80
  const padding = 4
  const min = Math.min(...data)
  const max = Math.max(...data)
  const range = max - min || 1

  const points = data
    .map((val, i) => {
      const x = padding + (i / (data.length - 1)) * (width - padding * 2)
      const y = height - padding - ((val - min) / range) * (height - padding * 2)
      return `${x},${y}`
    })
    .join(' ')

  const firstX = padding
  const lastX = padding + ((data.length - 1) / (data.length - 1)) * (width - padding * 2)
  const areaPath = `M${firstX},${height} L${points.split(' ').map((p) => p).join(' L')} L${lastX},${height} Z`

  return (
    <svg viewBox={`0 0 ${width} ${height}`} className="w-full h-full" preserveAspectRatio="none">
      <defs>
        <linearGradient id={`grad-${id}`} x1="0" y1="0" x2="0" y2="1">
          <stop offset="0%" stopColor="rgb(74, 222, 128)" stopOpacity="0.15" />
          <stop offset="100%" stopColor="rgb(74, 222, 128)" stopOpacity="0" />
        </linearGradient>
      </defs>
      <path d={areaPath} fill={`url(#grad-${id})`} />
      <polyline
        points={points}
        fill="none"
        stroke="rgb(74, 222, 128)"
        strokeWidth="1.5"
        strokeLinejoin="round"
        strokeLinecap="round"
        vectorEffect="non-scaling-stroke"
      />
    </svg>
  )
}

// Check if an ID is a real UUID (from the database) vs a mock short ID
function isRealId(id: string): boolean {
  return id.length > 10 && id.includes('-')
}

export default function MarketplacePage() {
  const { session } = useAuth()
  const router = useRouter()
  const [activeCategory, setActiveCategory] = useState('All')
  const [priceFilter, setPriceFilter] = useState<'all' | 'free' | 'paid'>('all')
  const [search, setSearch] = useState('')
  const [selectedStrategy, setSelectedStrategy] = useState<MockStrategy | null>(null)
  const [carouselSlide, setCarouselSlide] = useState(0)
  const [previewMode, setPreviewMode] = useState(false)
  const strategies = mockStrategies

  const [purchasing, setPurchasing] = useState(false)
  const [showPaymentConfirm, setShowPaymentConfirm] = useState(false)
  const [pendingStrategy, setPendingStrategy] = useState<MockStrategy | null>(null)

  const handleGetStrategy = async (strategy: MockStrategy) => {
    if (!session?.access_token) { toast.error('Please log in'); return }

    // If paid, show confirmation first
    if (strategy.price !== 'Free' && strategy.priceCents > 0) {
      setPendingStrategy(strategy)
      setShowPaymentConfirm(true)
      return
    }

    // Free — copy directly
    await copyStrategyToCollection(strategy)
  }

  const copyStrategyToCollection = async (strategy: MockStrategy) => {
    if (!session?.access_token) return
    setPurchasing(true)
    try {
      // For real DB strategies, use the purchase API
      if (isRealId(strategy.id)) {
        const res = await fetch('/api/marketplace/purchase', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${session.access_token}` },
          body: JSON.stringify({ strategy_id: strategy.id }),
        })
        const data = await res.json()
        if (res.status === 402) {
          toast.error(data.message || 'Insufficient credits')
          setShowPaymentConfirm(false)
          return
        }
        if (res.status === 409) {
          toast.info('You already own this strategy!')
          setShowPaymentConfirm(false)
          setSelectedStrategy(null)
          return
        }
        if (!res.ok) throw new Error(data.error)
        toast.success(data.purchased ? 'Strategy purchased!' : 'Strategy added!')
      } else {
        // Mock strategy — create directly in user's strategies
        const res = await fetch('/api/strategies', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${session.access_token}` },
          body: JSON.stringify({
            name: strategy.name,
            market: strategy.market,
            description: strategy.description,
            tags: strategy.tags,
            status: 'backtested',
            mql5_code: strategy.mqlCode || null,
            platform: strategy.platform,
            sharpe_ratio: strategy.sharpe,
            max_drawdown: strategy.drawdown,
            win_rate: strategy.winRate,
            total_return: strategy.totalReturn,
            strategy_summary: {
              entry_rules: strategy.entryRules,
              exit_rules: strategy.exitRules,
              risk_logic: strategy.riskLogic,
            },
          }),
        })
        if (!res.ok) throw new Error('Failed to add strategy')
        toast.success('Strategy added to your collection!')
      }
      setShowPaymentConfirm(false)
      setSelectedStrategy(null)
    } catch (e: any) {
      toast.error(e.message || 'Failed to add strategy')
    } finally {
      setPurchasing(false)
    }
  }

  const handlePreview = (strategy: MockStrategy) => {
    // Create a strategy in collection and open in AI builder
    handleGetStrategy(strategy)
  }

  const filtered = strategies.filter((s) => {
    // Price filter
    if (priceFilter === 'free' && s.priceCents > 0) return false
    if (priceFilter === 'paid' && s.priceCents <= 0) return false
    // Category filter
    if (activeCategory !== 'All') {
      if (activeCategory === 'Gold' && !s.market.includes('XAU')) return false
      if (activeCategory === 'Forex' && !['EURUSD', 'GBPUSD', 'USDJPY'].includes(s.market)) return false
      if (activeCategory === 'Crypto' && !['BTCUSD', 'ETHUSD'].includes(s.market)) return false
      if (activeCategory === 'Scalping' && !s.tags.some(t => t.toLowerCase() === 'scalping')) return false
      if (activeCategory === 'Mean Reversion' && !s.tags.some(t => t.toLowerCase() === 'mean reversion')) return false
      if (activeCategory === 'Breakout' && !s.tags.some(t => t.toLowerCase() === 'breakout')) return false
      if (activeCategory === 'Trend Following' && !s.tags.some(t => t.toLowerCase() === 'trend following')) return false
    }
    if (search) {
      const q = search.toLowerCase()
      if (!s.name.toLowerCase().includes(q) && !s.author.toLowerCase().includes(q) && !s.market.toLowerCase().includes(q)) return false
    }
    return true
  })

  const openModal = (s: MockStrategy) => {
    setSelectedStrategy(s)
    setCarouselSlide(0)
    setPreviewMode(false)
  }

  // "Slides" for the modal carousel — we show equity curve + stats views
  const slides = selectedStrategy ? [
    { type: 'equity' as const, label: 'Equity Curve' },
    { type: 'metrics' as const, label: 'Performance Metrics' },
    { type: 'rules' as const, label: 'Strategy Rules' },
  ] : []

  return (
    <PageTransition className="p-6 sm:p-8 lg:p-10 space-y-6 max-w-[1400px]">
      {/* Header */}
      <div>
        <h1 className="text-[32px] font-bold tracking-[-0.04em] text-foreground">
          Strategy Templates
        </h1>
        <p className="text-[16px] text-foreground/40 mt-1">
          Explore a curated collection of strategies built by our community.
        </p>
      </div>

      {/* Search bar */}
      <div className="flex items-center gap-4">
        <div className="relative flex-1 max-w-[420px]">
          <Search size={16} className="absolute left-4 top-1/2 -translate-y-1/2 text-foreground/25" />
          <input
            type="text"
            placeholder="Search strategies..."
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            className="w-full rounded-full border border-foreground/[0.08] bg-transparent pl-10 pr-4 py-2.5 text-[14px] text-foreground/80 placeholder:text-foreground/25 focus:outline-none focus:border-foreground/[0.16] transition-colors"
          />
        </div>
      </div>

      {/* Divider */}
      <div className="h-px bg-foreground/[0.06]" />

      {/* Filters */}
      <div className="flex gap-4 flex-wrap items-center">
        {/* Price filter */}
        <div className="flex gap-1 rounded-xl bg-foreground/[0.03] border border-foreground/[0.06] p-0.5">
          {(['all', 'free', 'paid'] as const).map((f) => (
            <button
              key={f}
              onClick={() => setPriceFilter(f)}
              className={cn(
                'rounded-lg px-3.5 py-1.5 text-[12px] font-medium transition-all capitalize',
                priceFilter === f
                  ? 'bg-foreground text-background shadow-sm'
                  : 'text-foreground/40 hover:text-foreground/70'
              )}
            >
              {f === 'all' ? 'All' : f === 'free' ? 'Free' : 'Paid'}
            </button>
          ))}
        </div>

        <div className="w-px h-5 bg-foreground/[0.08]" />

        {/* Category pills */}
        <div className="flex gap-1.5 flex-wrap items-center">
          {categories.map((cat) => (
            <button
              key={cat}
              onClick={() => setActiveCategory(cat)}
              className={cn(
                'rounded-full px-3 py-1 text-[12px] font-medium transition-all',
                activeCategory === cat
                  ? 'bg-foreground/[0.08] text-foreground'
                  : 'text-foreground/30 hover:text-foreground/60'
              )}
            >
              {cat}
            </button>
          ))}
        </div>
      </div>

      {/* Strategy cards grid — apptemplate style */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-x-8 gap-y-10 mt-2">
        {filtered.map((s, idx) => (
          <div
            key={s.id}
            className="group cursor-pointer flex flex-col gap-3"
            onClick={() => openModal(s)}
          >
            {/* Thumbnail — rich card with chart + metrics */}
            <div className="relative aspect-[16/10] rounded-xl overflow-hidden border border-foreground/[0.06] bg-card">
              {/* Subtle gradient bg */}
              <div className={`absolute inset-0 bg-gradient-to-br ${gradients[idx % gradients.length]} opacity-40`} />
              {/* Grid pattern overlay */}
              <svg className="absolute inset-0 w-full h-full opacity-[0.03]" xmlns="http://www.w3.org/2000/svg">
                <defs>
                  <pattern id={`grid-${s.id}`} width="20" height="20" patternUnits="userSpaceOnUse">
                    <path d="M 20 0 L 0 0 0 20" fill="none" stroke="currentColor" strokeWidth="0.5" />
                  </pattern>
                </defs>
                <rect width="100%" height="100%" fill={`url(#grid-${s.id})`} />
              </svg>
              {/* Equity curve — full bleed */}
              <div className="absolute inset-x-0 bottom-0 h-[65%] px-2">
                <EquityCurveSVG data={s.equityCurve} id={s.id} />
              </div>
              {/* Top-left: market + timeframe tags */}
              <div className="absolute top-3 left-3 flex items-center gap-1.5">
                <span className="rounded-md bg-black/40 backdrop-blur-sm px-2 py-0.5 text-[10px] font-semibold text-white/80">
                  {s.market}
                </span>
                {s.tags.find(t => ['M1','M5','M15','H1','H4','D1'].includes(t)) && (
                  <span className="rounded-md bg-black/30 backdrop-blur-sm px-1.5 py-0.5 text-[9px] font-medium text-white/60">
                    {s.tags.find(t => ['M1','M5','M15','H1','H4','D1'].includes(t))}
                  </span>
                )}
                <span className="rounded-md bg-blue-500/30 backdrop-blur-sm px-1.5 py-0.5 text-[9px] font-medium text-blue-300">
                  {s.platform.toUpperCase()}
                </span>
              </div>
              {/* Top-right: return badge */}
              <div className="absolute top-3 right-3">
                <span className={cn(
                  'rounded-md backdrop-blur-sm px-2 py-0.5 text-[11px] font-bold tabular-nums',
                  s.totalReturn >= 0 ? 'bg-emerald-500/20 text-emerald-300' : 'bg-red-500/20 text-red-300'
                )}>
                  {s.totalReturn >= 0 ? '+' : ''}{s.totalReturn.toFixed(1)}%
                </span>
              </div>
              {/* Bottom metrics bar */}
              <div className="absolute bottom-0 inset-x-0 bg-gradient-to-t from-black/60 via-black/30 to-transparent pt-8 pb-2.5 px-3">
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-3">
                    <div>
                      <span className="text-[8px] text-white/40 font-semibold uppercase tracking-wider">Sharpe</span>
                      <p className="text-[12px] font-bold text-white/90 tabular-nums">{s.sharpe.toFixed(2)}</p>
                    </div>
                    <div className="w-px h-5 bg-white/10" />
                    <div>
                      <span className="text-[8px] text-white/40 font-semibold uppercase tracking-wider">DD</span>
                      <p className="text-[12px] font-bold text-red-300/90 tabular-nums">{s.drawdown.toFixed(1)}%</p>
                    </div>
                    <div className="w-px h-5 bg-white/10" />
                    <div>
                      <span className="text-[8px] text-white/40 font-semibold uppercase tracking-wider">Win</span>
                      <p className="text-[12px] font-bold text-white/90 tabular-nums">{s.winRate.toFixed(0)}%</p>
                    </div>
                  </div>
                </div>
              </div>
              {/* Hover overlay */}
              <div className="absolute inset-0 bg-black/50 opacity-0 group-hover:opacity-100 transition-opacity duration-200 flex items-center justify-center">
                <span className="bg-white text-black rounded-lg px-6 py-2 text-[13px] font-medium shadow-lg">
                  View details
                </span>
              </div>
            </div>

            {/* Info below thumbnail */}
            <div className="flex items-start gap-3">
              {/* Creator avatar */}
              {s.isSigx ? (
                <div className="h-8 w-8 shrink-0 rounded-full bg-white flex items-center justify-center mt-0.5">
                  <span className="text-[8px] font-black text-black tracking-[-0.06em]">SX</span>
                </div>
              ) : (
                <div className="h-8 w-8 shrink-0 rounded-full bg-gradient-to-br from-foreground/[0.08] to-foreground/[0.04] flex items-center justify-center mt-0.5">
                  <span className="text-[10px] font-bold text-foreground/50">{s.author.slice(0, 2).toUpperCase()}</span>
                </div>
              )}
              <div className="flex-1 min-w-0">
                <p className="text-[15px] font-medium text-foreground/85 truncate">{s.name}</p>
                <div className="flex items-center gap-1.5 mt-0.5">
                  <span className={cn('text-[13px] font-medium', s.isSigx ? 'text-foreground/60' : 'text-foreground/40')}>
                    {s.author}
                  </span>
                  {s.isSigx && (
                    <svg viewBox="0 0 16 16" className="h-3.5 w-3.5 text-blue-400" fill="currentColor">
                      <path d="M8 0a8 8 0 100 16A8 8 0 008 0zm3.65 5.85l-4.5 4.5a.5.5 0 01-.7 0l-2-2a.5.5 0 01.7-.7L6.8 9.3l4.15-4.15a.5.5 0 01.7.7z" />
                    </svg>
                  )}
                  <span className="text-foreground/15">&middot;</span>
                  <Users size={12} className="text-foreground/25" />
                  <span className="text-[12px] text-foreground/35">{s.copies}</span>
                </div>
              </div>
              <span className={cn(
                'text-[14px] font-medium shrink-0 mt-1',
                s.price === 'Free' ? 'text-foreground/40' : 'text-foreground/80'
              )}>
                {s.price}
              </span>
            </div>

            {/* Tags */}
            <div className="flex gap-1.5 flex-wrap">
              {s.tags.slice(0, 2).map((tag) => (
                <span key={tag} className="rounded-md bg-foreground/[0.04] px-2.5 py-1 text-[11px] font-medium text-foreground/45">
                  {tag}
                </span>
              ))}
              {s.tags.length > 2 && (
                <span className="text-[11px] text-foreground/25 font-medium py-1">+{s.tags.length - 2}</span>
              )}
            </div>
          </div>
        ))}
      </div>

      {filtered.length === 0 && (
        <div className="flex flex-col items-center justify-center py-24 text-center">
          <Search size={32} className="text-foreground/10 mb-4" />
          <h2 className="text-[18px] font-bold text-foreground/60 tracking-[-0.02em]">No results</h2>
          <p className="text-[13px] text-foreground/20 mt-1 font-medium">No strategies match your filters.</p>
        </div>
      )}

      {/* ========== Strategy Detail Modal — apptemplatemodal style ========== */}
      <Dialog open={!!selectedStrategy} onOpenChange={(open) => !open && setSelectedStrategy(null)}>
        {selectedStrategy && (
          <DialogContent showCloseButton={true} className="bg-card border-foreground/[0.08] sm:max-w-[900px] p-0 overflow-hidden">
            <div className="flex flex-col sm:flex-row max-h-[80vh]">
              {/* Left panel — Carousel or Full Preview */}
              <div className="sm:w-[55%] bg-secondary relative flex flex-col">
                {previewMode ? (
                  /* Full preview — all backtest data in one scrollable view */
                  <div className="flex-1 overflow-y-auto p-6 space-y-5">
                    {/* Back button */}
                    <button
                      onClick={() => setPreviewMode(false)}
                      className="flex items-center gap-1.5 text-[12px] font-medium text-foreground/40 hover:text-foreground/60 transition-colors"
                    >
                      <ChevronLeft size={14} />
                      Back
                    </button>

                    {/* Equity curve */}
                    <div>
                      <h3 className="text-[11px] font-semibold text-foreground/30 uppercase tracking-wider mb-2">Equity Curve</h3>
                      <div className="h-[140px] w-full rounded-xl bg-foreground/[0.03] p-3">
                        <EquityCurveSVG data={selectedStrategy.equityCurve} id={`preview-${selectedStrategy.id}`} />
                      </div>
                    </div>

                    {/* All metrics */}
                    <div>
                      <h3 className="text-[11px] font-semibold text-foreground/30 uppercase tracking-wider mb-2">Performance Metrics</h3>
                      <div className="grid grid-cols-3 gap-2">
                        {[
                          { label: 'Sharpe', value: selectedStrategy.sharpe.toFixed(2), positive: selectedStrategy.sharpe > 1 },
                          { label: 'Annual Return', value: `+${selectedStrategy.annualReturn.toFixed(1)}%`, positive: true },
                          { label: 'Total Return', value: `+${selectedStrategy.totalReturn.toFixed(1)}%`, positive: true },
                          { label: 'Max Drawdown', value: `${selectedStrategy.drawdown.toFixed(1)}%`, positive: false },
                          { label: 'Win Rate', value: `${selectedStrategy.winRate.toFixed(1)}%`, positive: selectedStrategy.winRate > 50 },
                          { label: 'Copies', value: `${selectedStrategy.copies}`, positive: true },
                        ].map((m) => (
                          <div key={m.label} className="rounded-lg bg-foreground/[0.04] p-3 text-center">
                            <p className="text-[9px] text-foreground/25 font-semibold uppercase tracking-wider">{m.label}</p>
                            <p className={cn('text-[15px] font-bold tabular-nums mt-0.5', m.positive ? 'text-emerald-400/70' : 'text-red-400/70')}>
                              {m.value}
                            </p>
                          </div>
                        ))}
                      </div>
                    </div>

                    {/* Strategy rules */}
                    <div>
                      <div className="flex items-center gap-1.5 text-[11px] font-semibold text-foreground/30 uppercase tracking-wider mb-2">
                        <Target size={11} /> Entry Rules
                      </div>
                      <ul className="space-y-1.5 pl-4">
                        {selectedStrategy.entryRules.map((r, i) => (
                          <li key={i} className="list-disc text-[13px] text-foreground/50">{r}</li>
                        ))}
                      </ul>
                    </div>
                    <div>
                      <div className="flex items-center gap-1.5 text-[11px] font-semibold text-foreground/30 uppercase tracking-wider mb-2">
                        <BarChart3 size={11} /> Exit Rules
                      </div>
                      <ul className="space-y-1.5 pl-4">
                        {selectedStrategy.exitRules.map((r, i) => (
                          <li key={i} className="list-disc text-[13px] text-foreground/50">{r}</li>
                        ))}
                      </ul>
                    </div>
                    <div>
                      <div className="flex items-center gap-1.5 text-[11px] font-semibold text-foreground/30 uppercase tracking-wider mb-2">
                        <Shield size={11} /> Risk Management
                      </div>
                      <p className="text-[13px] text-foreground/50">{selectedStrategy.riskLogic}</p>
                    </div>

                    {/* MQL5 Code preview */}
                    {selectedStrategy.mqlCode && (
                      <div>
                        <h3 className="text-[11px] font-semibold text-foreground/30 uppercase tracking-wider mb-2">MQL5 Code</h3>
                        <pre className="rounded-xl bg-foreground/[0.04] p-4 text-[11px] text-foreground/50 font-mono overflow-x-auto max-h-[200px] overflow-y-auto leading-relaxed">
                          {selectedStrategy.mqlCode}
                        </pre>
                      </div>
                    )}
                  </div>
                ) : (
                  /* Carousel view */
                  <>
                    <div className="flex-1 flex items-center justify-center p-6 min-h-[300px] sm:min-h-0">
                      {carouselSlide === 0 && (
                        <div className="w-full space-y-4">
                          <div className="h-[160px] w-full">
                            <EquityCurveSVG data={selectedStrategy.equityCurve} id={`modal-${selectedStrategy.id}`} />
                          </div>
                          <div className="grid grid-cols-4 gap-2">
                            <div className="rounded-lg bg-foreground/[0.04] p-3 text-center">
                              <p className="text-[9px] text-foreground/30 font-semibold uppercase tracking-wider">Sharpe</p>
                              <p className="text-[16px] font-bold text-foreground/70 tabular-nums mt-0.5">{selectedStrategy.sharpe.toFixed(2)}</p>
                            </div>
                            <div className="rounded-lg bg-foreground/[0.04] p-3 text-center">
                              <p className="text-[9px] text-foreground/30 font-semibold uppercase tracking-wider">Drawdown</p>
                              <p className="text-[16px] font-bold text-red-400/70 tabular-nums mt-0.5">{selectedStrategy.drawdown.toFixed(1)}%</p>
                            </div>
                            <div className="rounded-lg bg-foreground/[0.04] p-3 text-center">
                              <p className="text-[9px] text-foreground/30 font-semibold uppercase tracking-wider">Win Rate</p>
                              <p className="text-[16px] font-bold text-foreground/70 tabular-nums mt-0.5">{selectedStrategy.winRate.toFixed(1)}%</p>
                            </div>
                            <div className="rounded-lg bg-foreground/[0.04] p-3 text-center">
                              <p className="text-[9px] text-foreground/30 font-semibold uppercase tracking-wider">Return</p>
                              <p className="text-[16px] font-bold text-emerald-400/70 tabular-nums mt-0.5">+{selectedStrategy.totalReturn.toFixed(1)}%</p>
                            </div>
                          </div>
                        </div>
                      )}
                      {carouselSlide === 1 && (
                        <div className="w-full space-y-3">
                          <div className="grid grid-cols-2 gap-3">
                            {[
                              { label: 'Sharpe Ratio', value: selectedStrategy.sharpe.toFixed(2), positive: selectedStrategy.sharpe > 1 },
                              { label: 'Annual Return', value: `+${selectedStrategy.annualReturn.toFixed(1)}%`, positive: true },
                              { label: 'Total Return', value: `+${selectedStrategy.totalReturn.toFixed(1)}%`, positive: true },
                              { label: 'Max Drawdown', value: `${selectedStrategy.drawdown.toFixed(1)}%`, positive: false },
                              { label: 'Win Rate', value: `${selectedStrategy.winRate.toFixed(1)}%`, positive: selectedStrategy.winRate > 50 },
                              { label: 'Copies', value: `${selectedStrategy.copies}`, positive: true },
                            ].map((m) => (
                              <div key={m.label} className="rounded-lg bg-foreground/[0.04] p-4">
                                <p className="text-[10px] text-foreground/30 font-semibold uppercase tracking-wider">{m.label}</p>
                                <p className={cn('text-[18px] font-bold tabular-nums mt-1', m.positive ? 'text-emerald-400/70' : 'text-red-400/70')}>
                                  {m.value}
                                </p>
                              </div>
                            ))}
                          </div>
                        </div>
                      )}
                      {carouselSlide === 2 && (
                        <div className="w-full space-y-5 overflow-y-auto max-h-[350px]">
                          <div>
                            <div className="flex items-center gap-1.5 text-[10px] font-semibold text-foreground/30 uppercase tracking-wider mb-2">
                              <Target size={11} /> Entry Rules
                            </div>
                            <ul className="space-y-1.5 pl-4">
                              {selectedStrategy.entryRules.map((r, i) => (
                                <li key={i} className="list-disc text-[13px] text-foreground/50">{r}</li>
                              ))}
                            </ul>
                          </div>
                          <div>
                            <div className="flex items-center gap-1.5 text-[10px] font-semibold text-foreground/30 uppercase tracking-wider mb-2">
                              <BarChart3 size={11} /> Exit Rules
                            </div>
                            <ul className="space-y-1.5 pl-4">
                              {selectedStrategy.exitRules.map((r, i) => (
                                <li key={i} className="list-disc text-[13px] text-foreground/50">{r}</li>
                              ))}
                            </ul>
                          </div>
                          <div>
                            <div className="flex items-center gap-1.5 text-[10px] font-semibold text-foreground/30 uppercase tracking-wider mb-2">
                              <Shield size={11} /> Risk Management
                            </div>
                            <p className="text-[13px] text-foreground/50">{selectedStrategy.riskLogic}</p>
                          </div>
                        </div>
                      )}
                    </div>

                    {/* Carousel navigation */}
                    <div className="flex items-center justify-between px-4 pb-4">
                      <button
                        onClick={() => setCarouselSlide(Math.max(0, carouselSlide - 1))}
                        disabled={carouselSlide === 0}
                        className="h-9 w-9 rounded-full bg-foreground/[0.06] flex items-center justify-center text-foreground/50 hover:bg-foreground/[0.1] transition-colors disabled:opacity-30"
                      >
                        <ChevronLeft size={18} />
                      </button>
                      <div className="flex items-center gap-2">
                        {slides.map((_, i) => (
                          <button
                            key={i}
                            onClick={() => setCarouselSlide(i)}
                            className={cn(
                              'h-2 w-2 rounded-full transition-colors',
                              carouselSlide === i ? 'bg-foreground/70' : 'bg-foreground/20'
                            )}
                          />
                        ))}
                      </div>
                      <button
                        onClick={() => setCarouselSlide(Math.min(slides.length - 1, carouselSlide + 1))}
                        disabled={carouselSlide === slides.length - 1}
                        className="h-9 w-9 rounded-full bg-foreground/[0.06] flex items-center justify-center text-foreground/50 hover:bg-foreground/[0.1] transition-colors disabled:opacity-30"
                      >
                        <ChevronRight size={18} />
                      </button>
                    </div>
                  </>
                )}
              </div>

              {/* Right panel — Details */}
              <div className="sm:w-[45%] overflow-y-auto p-6 space-y-5">
                {/* Title */}
                <h2 className="text-[22px] font-bold tracking-[-0.02em] text-foreground leading-tight">
                  {selectedStrategy.name}
                </h2>

                {/* Author + usages */}
                <div className="flex items-center gap-2 text-[13px]">
                  {selectedStrategy.isSigx ? (
                    <div className="h-6 w-6 rounded-full bg-white flex items-center justify-center">
                      <span className="text-[7px] font-black text-black tracking-[-0.06em]">SX</span>
                    </div>
                  ) : (
                    <div className="h-6 w-6 rounded-full bg-foreground/[0.06] flex items-center justify-center text-[9px] font-bold text-foreground/50">
                      {selectedStrategy.author.slice(0, 2).toUpperCase()}
                    </div>
                  )}
                  <span className="text-foreground/50">by {selectedStrategy.author}</span>
                  {selectedStrategy.isSigx && (
                    <svg viewBox="0 0 16 16" className="h-3.5 w-3.5 text-blue-400" fill="currentColor">
                      <path d="M8 0a8 8 0 100 16A8 8 0 008 0zm3.65 5.85l-4.5 4.5a.5.5 0 01-.7 0l-2-2a.5.5 0 01.7-.7L6.8 9.3l4.15-4.15a.5.5 0 01.7.7z" />
                    </svg>
                  )}
                  <span className="text-foreground/20">&middot;</span>
                  <span className="text-foreground/40">{selectedStrategy.copies} copies</span>
                </div>

                {/* Action buttons */}
                <div className="flex gap-3">
                  <button
                    onClick={() => handleGetStrategy(selectedStrategy)}
                    className="flex-1 rounded-xl bg-white px-4 py-2.5 text-[14px] font-semibold text-black hover:bg-white/90 transition-colors text-center"
                  >
                    {selectedStrategy.price === 'Free' ? 'Get for Free' : `Purchase for ${selectedStrategy.price}`}
                  </button>
                  <button
                    onClick={() => setPreviewMode(!previewMode)}
                    className={cn(
                      'rounded-xl border px-4 py-2.5 text-[14px] font-medium transition-colors flex items-center gap-2',
                      previewMode
                        ? 'border-foreground/[0.15] bg-foreground/[0.06] text-foreground/80'
                        : 'border-foreground/[0.08] text-foreground/70 hover:bg-foreground/[0.04]'
                    )}
                  >
                    <ExternalLink size={14} />
                    {previewMode ? 'Summary' : 'Preview'}
                  </button>
                </div>

                {/* Divider */}
                <div className="h-px bg-foreground/[0.06]" />

                {/* About */}
                <div>
                  <h3 className="text-[14px] font-semibold text-foreground/60 mb-3">About this strategy</h3>
                  {/* Tags */}
                  <div className="flex flex-wrap gap-2 mb-3">
                    {selectedStrategy.tags.map((tag) => (
                      <span key={tag} className="rounded-md bg-foreground/[0.04] border border-foreground/[0.04] px-2.5 py-1 text-[11px] text-foreground/45 font-medium">
                        {tag}
                      </span>
                    ))}
                    <span className="rounded-md bg-foreground/[0.04] border border-foreground/[0.04] px-2.5 py-1 text-[11px] text-foreground/45 font-medium">
                      {selectedStrategy.market}
                    </span>
                  </div>
                  <p className="text-[13px] text-foreground/45 leading-[1.65]">
                    {selectedStrategy.description}
                  </p>
                </div>

                {/* Price */}
                <div className="flex items-center justify-between py-3 px-4 rounded-xl bg-foreground/[0.03] border border-foreground/[0.04]">
                  <span className="text-[13px] text-foreground/50 font-medium">Price</span>
                  <span className={cn(
                    'text-[16px] font-bold',
                    selectedStrategy.price === 'Free' ? 'text-emerald-400/70' : 'text-foreground'
                  )}>
                    {selectedStrategy.price}
                  </span>
                </div>

                {/* Copy button (full width) */}
                <button
                  onClick={() => handleGetStrategy(selectedStrategy)}
                  className="w-full rounded-xl bg-foreground/[0.06] px-4 py-3 text-[14px] font-medium text-foreground/70 hover:bg-foreground/[0.1] transition-colors flex items-center justify-center gap-2"
                >
                  {selectedStrategy.price === 'Free' ? <><Copy size={14} /> Add to My Strategies</> : <><ShoppingCart size={14} /> Purchase Strategy</>}
                </button>
              </div>
            </div>
          </DialogContent>
        )}
      </Dialog>

      {/* Payment Confirmation */}
      <Dialog open={showPaymentConfirm} onOpenChange={setShowPaymentConfirm}>
        <DialogContent className="bg-card border-foreground/[0.08] sm:max-w-[420px] p-6">
          <div className="text-center space-y-4">
            <div className="h-14 w-14 rounded-2xl bg-orange-500/10 flex items-center justify-center mx-auto">
              <ShoppingCart size={24} className="text-orange-400" />
            </div>
            <div>
              <h2 className="text-[18px] font-bold text-foreground">Purchase Strategy</h2>
              <p className="text-[14px] text-foreground/40 mt-1">{pendingStrategy?.name}</p>
            </div>
            <div className="rounded-xl bg-foreground/[0.03] border border-foreground/[0.04] p-4 space-y-2">
              <div className="flex items-center justify-between text-[13px]">
                <span className="text-foreground/50">Price</span>
                <span className="font-bold text-foreground">{pendingStrategy?.price}</span>
              </div>
              <div className="flex items-center justify-between text-[13px]">
                <span className="text-foreground/50">Credits needed</span>
                <span className="font-bold text-foreground">{Math.ceil((pendingStrategy?.priceCents || 0) / 100)}</span>
              </div>
              <div className="flex items-center justify-between text-[13px]">
                <span className="text-foreground/50">Platform</span>
                <span className="font-semibold text-foreground/70">{pendingStrategy?.platform?.toUpperCase()}</span>
              </div>
              <div className="h-px bg-foreground/[0.06]" />
              <div className="flex items-center justify-between text-[13px]">
                <span className="text-foreground/50">Includes</span>
                <span className="text-foreground/60">Full source code + strategy rules</span>
              </div>
            </div>
            <p className="text-[12px] text-foreground/30">
              Credits will be deducted from your balance. The strategy with full MQL code will appear in your strategies.
            </p>
            <div className="flex gap-3">
              <button onClick={() => setShowPaymentConfirm(false)} className="flex-1 rounded-xl border border-foreground/[0.08] py-2.5 text-[13px] font-medium text-foreground/50 hover:bg-foreground/[0.04] transition-colors">
                Cancel
              </button>
              <button
                onClick={() => pendingStrategy && copyStrategyToCollection(pendingStrategy)}
                disabled={purchasing}
                className="flex-1 rounded-xl bg-white py-2.5 text-[13px] font-semibold text-black hover:bg-white/90 transition-colors disabled:opacity-50"
              >
                {purchasing ? 'Processing...' : `Pay ${pendingStrategy?.price}`}
              </button>
            </div>
          </div>
        </DialogContent>
      </Dialog>
    </PageTransition>
  )
}
