export interface BlogPost {
  slug: string
  title: string
  excerpt: string
  date: string
  category: string
  readTime: string
  content: string
}

export const posts: BlogPost[] = [
  {
    slug: 'why-ai-strategies-need-real-backtests',
    title: 'Why AI-Generated Trading Strategies Need Real Backtests',
    excerpt: 'Simulated results and curve-fitted models can look impressive on paper. Here\'s why SIGX runs every strategy through real MetaTrader 5 infrastructure — and what that means for your results.',
    date: 'March 20, 2026',
    category: 'Engineering',
    readTime: '5 min',
    content: `The promise of AI in trading is simple: describe what you want, and let the machine build it. But there's a critical gap between "the AI wrote some code" and "this strategy actually works."

## The Problem with Simulated Backtests

Most AI trading tools generate code and then run it through a simplified simulation — often just a loop over price data with basic fill logic. These simulations miss the details that make or break a strategy in live markets:

- **Spread and slippage** — Simulations often assume zero spread or fixed spread. In reality, spreads widen during news events and low-liquidity periods, eating into profits.
- **Tick-level execution** — A bar-level simulation can't tell you whether your stop loss would have been hit before your take profit within the same candle. MetaTrader 5's tick-based backtester can.
- **Broker-specific behavior** — Different brokers have different margin rules, symbol naming conventions, and execution policies. Real MT5 backtests use actual broker configurations.

## What SIGX Does Differently

Every strategy generated by SIGX goes through the MetaTrader 5 Strategy Tester — the same tool professional algo traders use. Here's the pipeline:

1. **AI generates MQL5 code** — Complete Expert Advisor with proper trade management, error handling, and input parameters.
2. **MetaEditor compiles it** — The official MQL5 compiler catches syntax errors, type mismatches, and deprecated function calls.
3. **Strategy Tester runs it** — Historical tick data, real spread modeling, accurate fill simulation.
4. **Report parsing** — We extract every metric from the official MT5 HTML report: profit factor, Sharpe ratio, max drawdown, recovery factor, and the full equity curve.

The result is a backtest you can trust — the same result you'd get if you ran it yourself in MetaTrader 5.

## Why This Matters

A strategy that looks profitable in a simplified simulation might fail catastrophically in a real backtest. Common reasons:

- **Overfitting to noise** — The AI optimized for historical patterns that don't repeat.
- **Unrealistic fills** — The simulation assumed orders fill at the exact price, ignoring gaps and requotes.
- **Ignored costs** — Commission, swap, and spread weren't factored in.

By running real backtests, SIGX catches these issues before you risk real capital. A strategy with a 1.8 profit factor in simulation might show 0.9 in a real backtest — and that's information you need.

## The Trade-Off

Real backtests take longer than simulations. A simulation runs in milliseconds; an MT5 backtest takes 30-90 seconds. We think the extra time is worth it. You're building trading strategies, not toy models.

That's why SIGX exists: to give every trader access to professional-grade backtesting infrastructure, powered by AI that writes real code.`,
  },
  {
    slug: 'understanding-profit-factor-sharpe-drawdown',
    title: 'Understanding Profit Factor, Sharpe Ratio, and Max Drawdown',
    excerpt: 'Three numbers that tell you almost everything about a trading strategy. A practical guide to reading backtest metrics without a finance degree.',
    date: 'March 15, 2026',
    category: 'Education',
    readTime: '7 min',
    content: `When you run a backtest on SIGX, you get a dashboard of metrics. Three of them matter more than the rest: Profit Factor, Sharpe Ratio, and Maximum Drawdown. Here's how to read them.

## Profit Factor

**What it is:** Total gross profit divided by total gross loss.

**How to read it:**
- **PF < 1.0** — The strategy loses money. Every dollar lost costs more than a dollar earned.
- **PF 1.0 - 1.2** — Barely profitable. Transaction costs or a few bad trades could flip it negative.
- **PF 1.2 - 1.5** — Decent. The strategy has a real edge, but it's modest.
- **PF 1.5 - 2.0** — Strong. This is the sweet spot for most robust strategies.
- **PF > 2.0** — Excellent, but verify it's not overfitted. Very high PFs on small sample sizes are suspicious.

**Example:** If a strategy made $10,000 in winning trades and lost $6,000 in losing trades, the profit factor is 10,000 / 6,000 = 1.67.

**Watch out for:** High profit factors with very few trades. A strategy with PF 3.0 but only 12 trades is not statistically meaningful.

## Sharpe Ratio

**What it is:** Risk-adjusted return. It measures how much return you get per unit of risk (volatility).

**How to read it:**
- **Sharpe < 0** — Negative returns. Avoid.
- **Sharpe 0 - 0.5** — Poor risk-adjusted returns. The volatility isn't worth the gain.
- **Sharpe 0.5 - 1.0** — Acceptable. Many real-world strategies fall here.
- **Sharpe 1.0 - 2.0** — Good. Strong risk-adjusted performance.
- **Sharpe > 2.0** — Excellent. Verify the sample size and check for overfitting.

**Why it matters:** Two strategies can have the same total return, but the one with a higher Sharpe ratio got there with less volatility — meaning smaller drawdowns and more consistent equity growth.

**Example:** Strategy A returns 50% with 25% volatility (Sharpe 2.0). Strategy B returns 50% with 50% volatility (Sharpe 1.0). Strategy A is objectively better — same return, half the risk.

## Maximum Drawdown

**What it is:** The largest peak-to-trough decline in the equity curve before a new high is reached.

**How to read it:**
- **DD < 5%** — Very conservative. Likely a low-frequency, low-risk strategy.
- **DD 5-15%** — Moderate. Comfortable for most traders.
- **DD 15-25%** — Aggressive. You need strong conviction and risk tolerance.
- **DD > 25%** — High risk. Most traders will abandon the strategy during the drawdown.

**Why it matters:** Drawdown tells you the worst-case pain you'll experience. A strategy that returns 100% annually but has a 60% max drawdown means at some point you'll watch your account drop by more than half. Can you stomach that?

**The psychological test:** Whatever the max drawdown was in backtesting, expect it to be worse in live trading. Markets are non-stationary — new volatility regimes appear. If you can't handle the backtest drawdown, you definitely can't handle the live version.

## Putting It Together

The ideal strategy has:
- **Profit Factor > 1.3** — Meaningful edge.
- **Sharpe Ratio > 0.8** — Reasonable risk-adjusted returns.
- **Max Drawdown < 20%** — Survivable worst case.
- **Total Trades > 100** — Statistical significance.

No single metric tells the full story. A high Sharpe with tiny returns might not be worth trading due to transaction costs. A high profit factor with massive drawdown might blow up your account before the edge plays out.

Use all three together, and always consider the number of trades. Metrics on 500+ trades are far more reliable than metrics on 30.`,
  },
  {
    slug: 'from-idea-to-expert-advisor',
    title: 'From Idea to Expert Advisor in 60 Seconds',
    excerpt: 'A walkthrough of the SIGX AI Builder — how natural language prompts become compiled MQL5 code, and what happens under the hood during each step.',
    date: 'March 10, 2026',
    category: 'Product',
    readTime: '4 min',
    content: `You type a sentence describing a trading strategy. 60 seconds later, you're looking at a compiled Expert Advisor with real backtest results. Here's what happens in between.

## Step 1: You Describe Your Strategy

Open the AI Builder and type something like:

> "RSI mean reversion on XAUUSD H1. Buy when RSI(14) drops below 30, sell when it goes above 70. Use ATR(14) for stop loss at 1.5x ATR and take profit at 2x ATR. Risk 1% per trade."

The more specific you are, the better the result. Mention:
- **Symbol and timeframe** — XAUUSD H1, EURUSD M15, etc.
- **Entry rules** — What triggers a buy or sell.
- **Exit rules** — Stop loss, take profit, trailing stop, time-based exits.
- **Risk management** — Lot sizing, max positions, risk per trade.

## Step 2: AI Generates MQL5 Code

Our AI writes a complete Expert Advisor in MQL5 — not a code snippet, but a full EA with:
- Proper OnInit(), OnDeinit(), and OnTick() functions
- Trade management with position sizing
- Input parameters so you can adjust settings later
- Error handling for common MT5 issues

The generated code typically runs 200-500 lines depending on complexity.

## Step 3: Compilation

The code is sent to MetaEditor on our MT5 infrastructure for compilation. If there are syntax errors — which happens occasionally with AI-generated code — the system automatically attempts to fix them. It can retry up to 3 times, each time feeding the compiler errors back to the AI for correction.

Most strategies compile on the first attempt. Complex strategies with multiple indicators or custom logic might need one fix cycle.

## Step 4: Backtest

Once compiled, the EA runs through MetaTrader 5's Strategy Tester:
- **Default period:** January 2023 to January 2025
- **Modeling:** Every tick (highest accuracy)
- **Initial deposit:** $10,000
- **Leverage:** 1:100

The backtest takes 30-90 seconds depending on the strategy complexity and the number of trades generated.

## Step 5: Results

You get a complete backtest report with:
- Profit Factor, Sharpe Ratio, Max Drawdown
- Win Rate, Total Trades, Net Profit
- Equity curve chart
- The full .mq5 source code to download

From here, you can:
- **Optimize** — Run multiple iterations where the AI improves the strategy based on backtest results.
- **Modify** — Tell the AI to change specific parameters ("increase the RSI period to 21" or "add an EMA filter").
- **Download** — Get the .mq5 file and run it on your own MT5 terminal.

## What Makes a Good Prompt

The difference between a mediocre strategy and a good one often comes down to the prompt. Here are patterns that work well:

**Specific:** "EMA(10)/EMA(30) crossover on EURUSD H1 with ATR-based stops" is better than "a moving average strategy."

**Risk-aware:** "Risk 1% per trade, max 2 concurrent positions" gives the AI constraints to work with.

**Session-aware:** "Only trade during London session (8:00-16:00 GMT)" reduces noise from thin markets.

**Multi-condition:** "Buy when RSI < 30 AND price is above EMA(200) AND ATR(14) > 10 points" produces more selective strategies with fewer but higher-quality trades.

The AI Builder is designed to iterate. Start with a simple idea, backtest it, then refine based on the results.`,
  },
  {
    slug: 'mean-reversion-on-gold',
    title: 'The Case for Mean Reversion on Gold',
    excerpt: 'XAUUSD has unique characteristics that make it well-suited for mean reversion strategies. We explore why, and share prompt templates that work well.',
    date: 'March 5, 2026',
    category: 'Strategy',
    readTime: '6 min',
    content: `Gold (XAUUSD) is one of the most popular instruments on SIGX, and mean reversion strategies consistently perform well on it. Here's why, and how to build them.

## Why Gold Suits Mean Reversion

Gold has several characteristics that favor mean reversion over trend following:

**1. Range-bound behavior within sessions.** Gold often establishes a range during the Asian session, breaks out during London, and reverts during New York. These intraday patterns create reliable mean reversion setups.

**2. High liquidity with controlled volatility.** Unlike crypto or small-cap forex pairs, XAUUSD has deep liquidity that prevents wild, unpredictable moves. Volatility is present but structured — it tends to cluster around news events rather than randomly.

**3. Strong support/resistance levels.** Gold respects round numbers and historical levels more than most instruments. When price deviates significantly from these levels, it tends to snap back.

**4. Institutional participation.** Central banks, hedge funds, and physical gold markets create natural buying and selling pressure at extreme levels, providing the "force" that drives mean reversion.

## Indicators That Work Well

Based on SIGX backtest data across hundreds of gold strategies, these indicators produce the best mean reversion results:

**Bollinger Bands (20, 2)** — The classic mean reversion indicator. Buy when price touches the lower band, sell when it touches the upper band. Works best on H1 and H4 timeframes.

**RSI (14)** — Oversold/overbought readings (30/70) are reliable on gold, especially when combined with a trend filter like EMA(200).

**Stochastic (14, 3, 3)** — Similar to RSI but with a smoothing component that reduces false signals. Works well on M30 and H1.

**ATR (14)** — Not a signal indicator, but essential for position sizing and stop placement. Gold's ATR varies significantly between sessions.

## Prompt Templates

Here are prompts that produce consistently profitable gold strategies on SIGX:

### Basic RSI Mean Reversion
> "RSI mean reversion on XAUUSD H1. Buy when RSI(14) drops below 30 and price is above EMA(200). Sell when RSI goes above 70 and price is below EMA(200). SL = 1.5 × ATR(14), TP = 2 × ATR(14). Risk 1% per trade."

### Bollinger Band Bounce
> "Bollinger Band bounce strategy on XAUUSD H1. Buy when price closes below lower BB(20,2) and RSI(14) < 35. Sell when price closes above upper BB(20,2) and RSI(14) > 65. Target the middle band. SL = 1.5 × ATR(14). Max 2 positions."

### Session-Based Range Reversion
> "XAUUSD H1 session strategy. Calculate the Asian session range (hours 0-8 GMT). If price breaks above the range during London (8-16), sell with SL above the high and TP at the range midpoint. If price breaks below, buy with SL below the low and TP at midpoint. Close all at hour 20."

## What to Watch For

Mean reversion strategies on gold fail in two scenarios:

**1. Strong trend days.** When gold moves 2-3% in a single direction (usually driven by Fed announcements or geopolitical events), mean reversion gets crushed. Always use stop losses.

**2. Low volatility compression.** When ATR drops significantly, the bands tighten and signals become unreliable. Consider adding an ATR filter — only trade when ATR(14) is above a minimum threshold.

## Typical Backtest Results

A well-constructed gold mean reversion strategy on SIGX typically shows:
- Profit Factor: 1.2 - 1.6
- Sharpe Ratio: 0.4 - 1.0
- Max Drawdown: 5% - 15%
- Win Rate: 48% - 55%
- Total Trades: 150-400 over 2 years

These aren't spectacular numbers, but they're consistent and realistic. Strategies showing PF > 2.0 on gold are likely overfitted.

The key is iterations. Start with a basic prompt, run a backtest, then refine. The AI Builder's optimization feature can run 3-5 iterations automatically, improving the strategy each time.`,
  },
  {
    slug: 'managing-risk-in-automated-trading',
    title: 'Managing Risk in Automated Trading',
    excerpt: 'Position sizing, drawdown limits, and correlation — the risk management fundamentals that separate profitable systems from blown accounts.',
    date: 'February 28, 2026',
    category: 'Education',
    readTime: '8 min',
    content: `The fastest way to lose money in automated trading isn't a bad strategy — it's bad risk management on a decent strategy. Here's what you need to know.

## Position Sizing: The Most Important Decision

How much you risk per trade matters more than your entry signal. There are three common approaches:

### Fixed Percentage Risk
Risk a fixed percentage of your account on each trade. The industry standard is 1-2%.

**How it works:** If your account is $10,000 and you risk 1%, your maximum loss per trade is $100. If your stop loss is 50 points, your lot size is calculated so that 50 points = $100.

**Why it works:** As your account grows, position sizes grow proportionally. As it shrinks, sizes shrink too — protecting you from ruin.

**In MQL5:** When building strategies on SIGX, include "Risk 1% per trade" in your prompt. The AI will implement proper lot size calculation based on account equity and stop loss distance.

### Fixed Lot Size
Trade the same lot size regardless of account size.

**When to use it:** Only for testing or very small accounts. This approach doesn't scale and doesn't protect against drawdowns.

### Kelly Criterion
The mathematically optimal position size based on your win rate and average win/loss ratio.

**In practice:** Full Kelly is too aggressive for most traders. Use "half Kelly" or "quarter Kelly" — divide the Kelly percentage by 2 or 4. This sacrifices some theoretical return for much better drawdown characteristics.

## Maximum Concurrent Positions

Running multiple trades simultaneously multiplies your risk. Two key rules:

**Rule 1:** Set a hard limit. Most strategies work well with 1-3 concurrent positions. Add "Max 2 concurrent positions" to your SIGX prompts.

**Rule 2:** Don't add to losing positions. If your first trade is underwater, opening a second trade in the same direction doubles your exposure to the same market condition that's already going against you.

## Drawdown Limits

Every strategy will have drawdowns. The question is: when do you stop?

**Daily drawdown limit:** Stop trading for the day if the account drops by a set percentage (e.g., 3%). This prevents a bad day from becoming a catastrophic day.

**Total drawdown limit:** If the strategy reaches its maximum historical drawdown (from backtesting), pause it and re-evaluate. If it exceeds the historical max by 50%, the strategy may have stopped working.

**In MQL5:** You can include these rules in your SIGX prompt: "Stop trading for the day if daily loss exceeds 3% of equity."

## Correlation Risk

Running two "different" strategies that both trade gold breakouts is not diversification — it's concentration risk with extra steps.

**How to diversify:**
- Trade different instruments (XAUUSD + EURUSD, not XAUUSD + XAGUSD)
- Use different strategy types (mean reversion + trend following)
- Use different timeframes (H1 + D1)

**The test:** During your worst backtest drawdown, would all your strategies lose money at the same time? If yes, you're not diversified.

## Stop Losses Are Not Optional

Every trade needs a stop loss. Period. Here's why:

- **Fat tails exist.** Markets can gap past your expected exit point. A stop loss limits the damage.
- **Internet goes down.** Your connection drops, your VPS crashes, your broker has issues. A stop loss is a server-side order that executes regardless of your connection.
- **Psychology.** Without a stop loss, a losing trade becomes a "position" you're "holding." It's the start of every blown account story.

**ATR-based stops** are the most robust approach. "SL = 1.5 × ATR(14)" adapts to current volatility — tight stops in calm markets, wider stops in volatile markets.

## Risk-Reward Ratio

Your risk-reward ratio determines how often you need to be right to make money:

- **1:1 RR** — You need > 50% win rate to profit (after costs).
- **1:2 RR** — You need > 33% win rate to profit.
- **1:3 RR** — You need > 25% win rate to profit.

Most SIGX strategies target 1:1.5 to 1:2 risk-reward. This gives a comfortable margin — you can be wrong more than half the time and still make money.

## The Practical Checklist

Before deploying any strategy from SIGX to a live account:

1. Does it risk ≤ 2% per trade?
2. Are concurrent positions limited?
3. Is there a stop loss on every trade?
4. Has it been backtested over 100+ trades?
5. Is the max drawdown something you can personally tolerate?
6. Is it uncorrelated with your other running strategies?

If any answer is "no," fix it before going live. The market will always be there tomorrow.`,
  },
  {
    slug: 'parallel-mt5-backtesting-infrastructure',
    title: 'How We Built a Parallel MT5 Backtesting Infrastructure',
    excerpt: 'Running multiple MetaTrader 5 instances in parallel with slot pooling. A technical deep-dive into the infrastructure behind SIGX backtests.',
    date: 'February 20, 2026',
    category: 'Engineering',
    readTime: '10 min',
    content: `When we started SIGX, backtesting was the bottleneck. MetaTrader 5's Strategy Tester is powerful but designed for a single user running one test at a time. We needed to support hundreds of concurrent users. Here's how we solved it.

## The Challenge

MetaTrader 5 is a Windows-native application. The Strategy Tester locks the terminal while running. You can't run two backtests in the same MT5 instance simultaneously.

The naive solution — one MT5 instance per user — doesn't scale. Each MT5 installation takes ~500MB of disk space and needs its own symbol data, configuration, and login credentials.

## The Slot Architecture

We built a "slot pool" system. Each slot is a portable MT5 installation that can run independently:

**Slot 0** is the main MT5 installation — registered with the broker, has all symbol data downloaded, and serves as the template.

**Slots 1-N** are lightweight copies created from Slot 0. Each copy shares the broker connection but has its own terminal directory, allowing independent operation.

When a backtest request arrives:
1. The system finds a free slot.
2. It copies the EA code into that slot's Experts directory.
3. MetaEditor compiles the EA.
4. The Strategy Tester runs the backtest.
5. Results are parsed from the HTML report.
6. The slot is released back to the pool.

Slots are only locked during compile + backtest (30-90 seconds). During AI code generation (which takes 15-30 seconds), no slot is needed. This means a pool of just 4 slots can handle 8-10 concurrent jobs efficiently.

## The Hybrid Manager

The Hybrid Manager is a FastAPI service running on the Windows VPS that orchestrates everything:

**Single endpoint, full pipeline.** One API call triggers the entire workflow — AI code generation, compilation, backtesting, result parsing, and optional multi-iteration optimization.

**SSE streaming.** Clients receive real-time progress updates via Server-Sent Events. Each stage (generating, compiling, backtesting, analyzing) emits events so the frontend can show live progress.

**Auto-fix pipeline.** If compilation fails, the manager feeds the compiler errors back to the AI for automatic correction, up to 3 attempts. This recovers from ~85% of initial compilation failures without user intervention.

## Compile Error Recovery

AI-generated code doesn't always compile on the first try. Common issues:
- Deprecated MQL5 functions (the AI's training data includes older MQL5 versions)
- Type mismatches between different MT5 build versions
- Missing includes or incorrect function signatures

The auto-fix pipeline works by sending the full compiler output back to the AI with the instruction "fix these errors." The AI reads the error messages, identifies the issues, and generates corrected code. Each retry takes ~10 seconds.

Success rates by attempt:
- First compile: ~70% success
- After 1 fix: ~90% success
- After 2 fixes: ~95% success
- After 3 fixes: ~98% success

The remaining 2% usually have fundamental logic issues that require human intervention — which is why we surface the errors to the user with a "Help me fix it" option.

## Report Parsing

MetaTrader 5's Strategy Tester outputs results as an HTML file. We parse this to extract:
- All trade records (entry/exit prices, profit, duration)
- Summary statistics (profit factor, Sharpe, drawdown)
- Equity curve data points for charting

The HTML format varies slightly between MT5 builds, so our parser handles multiple formats with fallback logic.

## Performance Numbers

With our current infrastructure:
- **Compile time:** 2-5 seconds
- **Backtest time:** 30-90 seconds (depends on trade count)
- **AI generation:** 15-30 seconds per iteration
- **Total pipeline:** ~60-120 seconds for a full generate → compile → backtest cycle

For optimization runs (multiple iterations), each subsequent iteration is faster because the AI only modifies the existing code rather than generating from scratch.

## What We Learned

**Windows is unavoidable.** MT5 only runs on Windows. Wine and emulation layers don't support the Strategy Tester reliably. We accepted this constraint and built around it.

**Slots are better than VMs.** Virtual machines add overhead and complexity. Portable MT5 installations in separate directories are simpler, faster to create, and easier to manage.

**Auto-fix is essential.** Without automatic compilation error recovery, every third strategy would fail and require manual intervention. The auto-fix pipeline transformed the user experience from frustrating to seamless.

**SSE beats polling.** Users want to see progress in real-time. Server-Sent Events provide a simple, reliable streaming mechanism without the complexity of WebSockets.`,
  },
]

export const categoryColors: Record<string, string> = {
  Engineering: 'text-blue-400/70 bg-blue-500/[0.06] border-blue-500/10',
  Education: 'text-emerald-400/70 bg-emerald-500/[0.06] border-emerald-500/10',
  Product: 'text-violet-400/70 bg-violet-500/[0.06] border-violet-500/10',
  Strategy: 'text-amber-400/70 bg-amber-500/[0.06] border-amber-500/10',
}
