import type { Metadata } from 'next'
import LegalLayout from '@/components/legal-layout'

export const metadata: Metadata = {
  title: 'Terms of Service — SIGX',
  description: 'Terms and conditions for using the SIGX AI trading strategy platform.',
}

export default function TermsPage() {
  return (
    <LegalLayout title="Terms of Service" lastUpdated="March 22, 2026">
      <section>
        <p>
          These Terms of Service (&quot;Terms&quot;) govern your use of the SIGX platform (&quot;Service&quot;) operated by SIGX (&quot;we,&quot; &quot;us,&quot; or &quot;our&quot;). By creating an account or using the Service, you agree to these Terms. If you do not agree, do not use the Service.
        </p>
      </section>

      <section>
        <h2>1. Service Description</h2>
        <p>
          SIGX is an AI-powered platform for generating, backtesting, optimizing, and deploying trading strategies for MetaTrader 5. The Service uses artificial intelligence to produce MQL5 Expert Advisors based on user prompts.
        </p>
        <p>
          <strong>The Service is a tool, not financial advice.</strong> See our <a href="/disclaimer">Disclaimer</a> for important information about the risks of AI-generated strategies and trading.
        </p>
      </section>

      <section>
        <h2>2. Eligibility</h2>
        <p>
          You must be at least 18 years old and legally able to enter into contracts to use the Service. By using SIGX, you represent that you meet these requirements.
        </p>
      </section>

      <section>
        <h2>3. Account</h2>
        <ul>
          <li>You are responsible for maintaining the confidentiality of your account credentials.</li>
          <li>You are responsible for all activity under your account.</li>
          <li>You must provide accurate and complete information when registering.</li>
          <li>One account per person. Shared or automated account access is prohibited.</li>
        </ul>
      </section>

      <section>
        <h2>4. Credits and Payment</h2>
        <ul>
          <li>Certain features require credits. Credits may be earned (e.g., referral bonuses) or purchased.</li>
          <li>Credits are non-transferable and non-refundable unless required by law.</li>
          <li>We reserve the right to change credit pricing and features at any time.</li>
          <li>Abuse of free credits, referral programs, or promotional offers may result in account suspension.</li>
        </ul>
      </section>

      <section>
        <h2>5. Acceptable Use</h2>
        <p>You agree NOT to:</p>
        <ul>
          <li>Use the Service for any unlawful purpose or in violation of any applicable laws or regulations</li>
          <li>Reverse engineer, decompile, or attempt to extract the source code of the Service</li>
          <li>Resell, redistribute, or sublicense the Service without authorization</li>
          <li>Overload, disrupt, or interfere with the Service or its infrastructure</li>
          <li>Create multiple accounts to abuse free credits or referral programs</li>
          <li>Use automated tools or bots to access the Service without permission</li>
          <li>Misrepresent AI-generated strategies as human-created when distributing to others</li>
        </ul>
      </section>

      <section>
        <h2>6. Intellectual Property</h2>

        <h3>Your Content</h3>
        <p>
          You retain ownership of the strategy prompts you provide and the MQL5 code generated for your account. You grant SIGX a limited license to process, store, and display your content as needed to provide the Service.
        </p>

        <h3>Our Content</h3>
        <p>
          The SIGX platform, branding, UI, documentation, and underlying technology are our intellectual property. You may not copy, modify, or distribute them without permission.
        </p>
      </section>

      <section>
        <h2>7. AI-Generated Content</h2>
        <p>
          Strategies generated by SIGX are produced by AI and may contain errors, produce unexpected results, or fail to perform as indicated by backtest metrics. You acknowledge that:
        </p>
        <ul>
          <li>AI output is not guaranteed to be accurate, complete, or profitable</li>
          <li>Backtest results are hypothetical and may not reflect real-world performance</li>
          <li>You are solely responsible for reviewing and testing any strategy before live deployment</li>
          <li>SIGX is not liable for losses resulting from the use of AI-generated strategies</li>
        </ul>
      </section>

      <section>
        <h2>8. Limitation of Liability</h2>
        <p>
          To the maximum extent permitted by law, SIGX and its founders, employees, and affiliates shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including but not limited to loss of profits, trading losses, data loss, or business interruption, arising from your use of the Service.
        </p>
        <p>
          Our total liability to you for any claims arising from the Service shall not exceed the amount you have paid to SIGX in the 12 months preceding the claim.
        </p>
      </section>

      <section>
        <h2>9. Disclaimer of Warranties</h2>
        <p>
          The Service is provided &quot;as is&quot; and &quot;as available&quot; without warranties of any kind, express or implied, including but not limited to implied warranties of merchantability, fitness for a particular purpose, and non-infringement. We do not warrant that the Service will be uninterrupted, error-free, or secure.
        </p>
      </section>

      <section>
        <h2>10. Indemnification</h2>
        <p>
          You agree to indemnify and hold harmless SIGX and its officers, directors, employees, and agents from any claims, damages, losses, or expenses (including legal fees) arising from your use of the Service, violation of these Terms, or your trading activities.
        </p>
      </section>

      <section>
        <h2>11. Termination</h2>
        <p>
          We may suspend or terminate your account at any time for violation of these Terms or for any other reason at our discretion. You may delete your account at any time by contacting us. Upon termination, your right to use the Service ceases immediately.
        </p>
      </section>

      <section>
        <h2>12. Changes to Terms</h2>
        <p>
          We may modify these Terms at any time. We will notify you of material changes through the platform or by email. Continued use of the Service after changes constitutes acceptance.
        </p>
      </section>

      <section>
        <h2>13. Governing Law</h2>
        <p>
          These Terms are governed by the laws of the jurisdiction in which SIGX operates, without regard to conflict of law principles.
        </p>
      </section>

      <section>
        <h2>14. Contact</h2>
        <p>
          Questions about these Terms? Contact us at <a href="mailto:legal@sigx.ai">legal@sigx.ai</a>.
        </p>
      </section>
    </LegalLayout>
  )
}
