import { createClient } from '@supabase/supabase-js'

const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL!
const SUPABASE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY!
const ANON_KEY = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!

async function run() {
  const adm = createClient(SUPABASE_URL, SUPABASE_KEY)
  const anon = createClient(SUPABASE_URL, ANON_KEY)
  const { data: users } = await adm.auth.admin.listUsers()
  await adm.auth.admin.updateUserById(users!.users[0].id, { password: 'Test123!' })
  const { data: sess } = await anon.auth.signInWithPassword({ email: users!.users[0].email!, password: 'Test123!' })
  const T = sess!.session!.access_token
  const H = { 'Content-Type': 'application/json', Authorization: 'Bearer ' + T }

  const BASE = 'http://localhost:3000'

  const mql5Code = `//+------------------------------------------------------------------+
//|                                Gold London Breakout Pro.mq5       |
//|                                Generated by SIGX                  |
//+------------------------------------------------------------------+
#property copyright "SIGX"
#property version   "2.10"
#include <Trade/Trade.mqh>
CTrade trade;
int handleEMA, handleATR, handleRSI;
input double RiskPercent = 1.0;
input int EMA_Fast = 9;
input int EMA_Slow = 21;
input int ATR_Period = 14;
input double TP_Multiplier = 2.5;
input double SL_Multiplier = 1.2;
input int LondonStart = 8;
input int LondonEnd = 12;
input int MaxPositions = 2;
input int MagicNumber = 202501;

int OnInit() {
    trade.SetExpertMagicNumber(MagicNumber);
    handleEMA = iMA(_Symbol, PERIOD_CURRENT, EMA_Fast, 0, MODE_EMA, PRICE_CLOSE);
    handleATR = iATR(_Symbol, PERIOD_CURRENT, ATR_Period);
    handleRSI = iRSI(_Symbol, PERIOD_CURRENT, 14, PRICE_CLOSE);
    return INIT_SUCCEEDED;
}
void OnTick() {
    if(!IsNewBar()) return;
    MqlDateTime dt; TimeToStruct(TimeCurrent(), dt);
    if(dt.hour < LondonStart || dt.hour >= LondonEnd) return;
    double ema[], atr[], rsi[];
    ArraySetAsSeries(ema, true); ArraySetAsSeries(atr, true); ArraySetAsSeries(rsi, true);
    CopyBuffer(handleEMA, 0, 0, 3, ema);
    CopyBuffer(handleATR, 0, 0, 3, atr);
    CopyBuffer(handleRSI, 0, 0, 3, rsi);
    double c1 = iClose(_Symbol, PERIOD_CURRENT, 1);
    double c2 = iClose(_Symbol, PERIOD_CURRENT, 2);
    if(c2 < ema[2] && c1 > ema[1] && rsi[1] > 50) {
        double p = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
        trade.Buy(0.01, _Symbol, p, p - atr[1]*SL_Multiplier, p + atr[1]*TP_Multiplier);
    }
    if(c2 > ema[2] && c1 < ema[1] && rsi[1] < 50) {
        double p = SymbolInfoDouble(_Symbol, SYMBOL_BID);
        trade.Sell(0.01, _Symbol, p, p + atr[1]*SL_Multiplier, p - atr[1]*TP_Multiplier);
    }
}
bool IsNewBar() { static datetime lb=0; datetime cb=iTime(_Symbol,PERIOD_CURRENT,0); if(cb!=lb){lb=cb;return true;} return false; }`

  const mql4Code = `//+------------------------------------------------------------------+
//|                                EUR/USD Swing Trader.mq4           |
//|                                Generated by SIGX                  |
//+------------------------------------------------------------------+
#property copyright "SIGX"
extern double RiskPercent = 0.5;
extern int MA_Fast = 20;
extern int MA_Slow = 50;
extern double TP_Pips = 150;
extern double SL_Pips = 80;
extern int MagicNumber = 301001;

int OnInit() { return INIT_SUCCEEDED; }
void OnTick() {
    if(OrdersTotal() >= 1) return;
    double maF1 = iMA(NULL,0,MA_Fast,0,MODE_EMA,PRICE_CLOSE,1);
    double maF2 = iMA(NULL,0,MA_Fast,0,MODE_EMA,PRICE_CLOSE,2);
    double maS1 = iMA(NULL,0,MA_Slow,0,MODE_EMA,PRICE_CLOSE,1);
    double maS2 = iMA(NULL,0,MA_Slow,0,MODE_EMA,PRICE_CLOSE,2);
    double macd = iMACD(NULL,0,12,26,9,PRICE_CLOSE,MODE_MAIN,1);
    double lots = 0.01;
    if(maF2 < maS2 && maF1 > maS1 && macd > 0)
        OrderSend(Symbol(),OP_BUY,lots,Ask,3,Ask-SL_Pips*Point,Ask+TP_Pips*Point,"SIGX",MagicNumber);
    if(maF2 > maS2 && maF1 < maS1 && macd < 0)
        OrderSend(Symbol(),OP_SELL,lots,Bid,3,Bid+SL_Pips*Point,Bid-TP_Pips*Point,"SIGX",MagicNumber);
}`

  const btcCode = `//+------------------------------------------------------------------+
//|                                BTC Volatility Capture.mq5         |
//|                                Generated by SIGX                  |
//+------------------------------------------------------------------+
#property copyright "SIGX"
#include <Trade/Trade.mqh>
CTrade trade;
input double Risk = 1.5;
input int BB_Period = 20;
input double BB_Dev = 2.0;
input int RSI_Period = 14;
input int Magic = 401001;
int hBB, hRSI;
int OnInit() { trade.SetExpertMagicNumber(Magic); hBB=iBands(_Symbol,PERIOD_H1,BB_Period,0,BB_Dev,PRICE_CLOSE); hRSI=iRSI(_Symbol,PERIOD_H1,RSI_Period,PRICE_CLOSE); return INIT_SUCCEEDED; }
void OnTick() {
    double bbu[],bbl[],rsi[];
    ArraySetAsSeries(bbu,true); ArraySetAsSeries(bbl,true); ArraySetAsSeries(rsi,true);
    CopyBuffer(hBB,1,0,3,bbu); CopyBuffer(hBB,2,0,3,bbl); CopyBuffer(hRSI,0,0,3,rsi);
    double c = iClose(_Symbol,PERIOD_H1,1);
    if(c < bbl[1] && rsi[1] < 25) trade.Buy(0.01,_Symbol,0,bbl[1],bbu[1],"SIGX BTC Long");
    if(c > bbu[1] && rsi[1] > 75) trade.Sell(0.01,_Symbol,0,bbu[1],bbl[1],"SIGX BTC Short");
}`

  const strategies = [
    {
      name: 'Gold London Breakout Pro', market: 'XAUUSD', timeframe: 'M5', platform: 'mql5', price_cents: 2999,
      sharpe_ratio: 2.45, max_drawdown: -3.8, win_rate: 68.2, total_return: 52.4,
      tags: ['Gold', 'Breakout', 'M5'], mql5_code: mql5Code,
      description: 'Professional London session breakout EA for XAUUSD. Identifies Asian range liquidity sweeps and enters on London open displacement. Features adaptive ATR-based position sizing and a built-in news filter.',
      strategy_summary: { entry_rules: ['Price crosses EMA during London session', 'RSI confirms direction', 'ATR filter for volatility'], exit_rules: ['TP at 2.5x ATR', 'SL at 1.2x ATR', 'Trailing stop after 1.5x ATR profit'], risk_logic: 'Risk 1% per trade. Max 2 positions.' },
    },
    {
      name: 'EUR/USD Swing Trader MT4', market: 'EURUSD', timeframe: 'H4', platform: 'mql4', price_cents: 1499,
      sharpe_ratio: 1.92, max_drawdown: -6.1, win_rate: 57.8, total_return: 34.6,
      tags: ['Forex', 'Trend Following', 'H4'], mql5_code: mql4Code,
      description: 'Swing trading EA for EUR/USD on H4. Uses EMA crossovers and MACD divergence. Compatible with MetaTrader 4.',
      strategy_summary: { entry_rules: ['EMA 20/50 crossover', 'MACD confirms trend'], exit_rules: ['TP 150 pips', 'SL 80 pips', 'Trail after 100 pips'], risk_logic: 'Risk 0.5% per trade. Max 1 position.' },
    },
    {
      name: 'BTC Volatility Capture Pro', market: 'BTCUSD', timeframe: 'H1', platform: 'mql5', price_cents: 4999,
      sharpe_ratio: 1.78, max_drawdown: -11.2, win_rate: 51.4, total_return: 72.8,
      tags: ['Crypto', 'Mean Reversion', 'H1'], mql5_code: btcCode,
      description: 'Advanced Bitcoin volatility capture for MT5. Uses Bollinger Bands and RSI for mean-reverting entries with adaptive position sizing.',
      strategy_summary: { entry_rules: ['Price below lower BB + RSI < 25', 'Volatility spike > 2 std dev'], exit_rules: ['Mean reversion to opposite BB', 'Time exit after 4h'], risk_logic: 'Risk 1.5%. Reduce size in high volatility.' },
    },
  ]

  console.log('\n══ CREATING PAID MARKETPLACE STRATEGIES ══\n')

  for (const s of strategies) {
    console.log(`Creating: ${s.name} ($${(s.price_cents / 100).toFixed(2)})...`)
    const cr = await fetch(`${BASE}/api/strategies`, {
      method: 'POST', headers: H, body: JSON.stringify({ ...s, is_public: false, status: 'backtested' }),
    })
    const cd = await cr.json()
    if (!cd.strategy?.id) { console.log('  ❌ Create failed:', cd.error); continue }
    console.log('  ✅ Created:', cd.strategy.id)

    const pr = await fetch(`${BASE}/api/marketplace/publish`, {
      method: 'POST', headers: H,
      body: JSON.stringify({ strategy_id: cd.strategy.id, price_cents: s.price_cents, seller_description: s.description }),
    })
    const pd = await pr.json()
    pr.ok ? console.log(`  ✅ Published at $${(s.price_cents / 100).toFixed(2)} | ${s.platform.toUpperCase()} | ${s.mql5_code.length} chars code`)
          : console.log('  ❌ Publish failed:', pd.error)
    console.log('')
  }

  // Verify
  console.log('══ MARKETPLACE ══\n')
  const mr = await fetch(`${BASE}/api/marketplace`, { headers: H })
  const md = await mr.json()
  console.log(`Total: ${md.strategies?.length} strategies\n`)
  md.strategies?.forEach((s: any) => {
    const price = s.price_cents ? `$${(s.price_cents / 100).toFixed(2)}` : 'Free'
    console.log(`  ${s.name} | ${price} | ${(s.platform || 'mql5').toUpperCase()} | code: ${s.mql5_code ? s.mql5_code.length + ' chars' : 'none'}`)
  })
  console.log('\n🎉 Done!\n')
}

run().catch(e => console.log('Error:', e.message))
