/**
 * Client-side template data — no filesystem access, just data.
 * Used to instantly display template results without any API calls.
 */

export interface ClientTemplate {
  id: string
  name: string
  prompt: string
  description: string
  market: string
  timeframe: string
  mql5Code: string
  strategySnapshot: {
    name: string
    market: string
    entry_rules: string[]
    exit_rules: string[]
    risk_logic: string
  }
  backtestResults: {
    sharpe: number
    max_drawdown: number
    win_rate: number
    total_return: number
    profit_factor: number
    total_trades: number
    net_profit: number
    equity_curve: { date: string; equity: number }[]
  }
}

export const CLIENT_TEMPLATES: ClientTemplate[] = [
  {
    id: 'london-breakout',
    name: 'London Breakout',
    prompt: 'Build a XAUUSD London session breakout strategy on H1. Trade breakouts of the Asian session range during London open hours (8-10). Use range height for SL (1x) and TP (2x). Close all positions at hour 20. Max 2 positions, 1% risk per trade.',
    description: 'Trades breakouts of the Asian session range during London open. Uses range-based SL/TP with session time filters.',
    market: 'XAUUSD',
    timeframe: 'H1',
    mql5Code: "//+------------------------------------------------------------------+\n//|                                         London_Breakout.mq5       |\n//|                                         Generated by SIGX         |\n//+------------------------------------------------------------------+\n#property copyright \"SIGX\"\n#property version   \"1.00\"\n#include <Trade/Trade.mqh>\n\ninput double RiskPercent    = 1.0;\ninput int    MagicNumber    = 200001;\ninput int    LondonStartHour = 8;    // London session start (server time)\ninput int    LondonEndHour   = 10;   // Breakout window end\ninput int    CloseHour       = 20;   // Close all trades\ninput int    RangeLookback   = 4;    // Hours before London to measure range\ninput double SL_Multiplier   = 1.0;  // SL = range height * multiplier\ninput double TP_Multiplier   = 2.0;  // TP = range height * multiplier\ninput int    MaxPositions    = 2;\n\nCTrade trade;\nint hATR;\n\nint OnInit() {\n    trade.SetExpertMagicNumber(MagicNumber);\n    hATR = iATR(_Symbol, PERIOD_H1, 14);\n    if(hATR == INVALID_HANDLE) return INIT_FAILED;\n    return INIT_SUCCEEDED;\n}\n\nvoid OnDeinit(const int reason) {\n    IndicatorRelease(hATR);\n}\n\nvoid OnTick() {\n    MqlDateTime dt;\n    TimeToStruct(TimeCurrent(), dt);\n\n    // Close all positions at CloseHour\n    if(dt.hour >= CloseHour) {\n        CloseAllPositions();\n        return;\n    }\n\n    // Only trade during London breakout window\n    if(dt.hour < LondonStartHour || dt.hour >= LondonEndHour) return;\n\n    static datetime lastBar = 0;\n    datetime currentBar = iTime(_Symbol, PERIOD_H1, 0);\n    if(currentBar == lastBar) return;\n    lastBar = currentBar;\n\n    if(CountPositions() >= MaxPositions) return;\n\n    // Calculate Asian session range (before London)\n    double rangeHigh = -999999, rangeLow = 999999;\n    for(int i = 1; i <= RangeLookback; i++) {\n        double h = iHigh(_Symbol, PERIOD_H1, i);\n        double l = iLow(_Symbol, PERIOD_H1, i);\n        if(h > rangeHigh) rangeHigh = h;\n        if(l < rangeLow)  rangeLow = l;\n    }\n\n    double rangeSize = rangeHigh - rangeLow;\n    if(rangeSize < _Point * 10) return; // Too narrow\n\n    double ask = SymbolInfoDouble(_Symbol, SYMBOL_ASK);\n    double bid = SymbolInfoDouble(_Symbol, SYMBOL_BID);\n    double sl = rangeSize * SL_Multiplier;\n    double tp = rangeSize * TP_Multiplier;\n    double lots = CalculateLotSize(sl);\n\n    // Breakout above range\n    if(ask > rangeHigh) {\n        trade.Buy(lots, _Symbol, ask, ask - sl, ask + tp);\n    }\n    // Breakout below range\n    if(bid < rangeLow) {\n        trade.Sell(lots, _Symbol, bid, bid + sl, bid - tp);\n    }\n}\n\nvoid CloseAllPositions() {\n    for(int i = PositionsTotal() - 1; i >= 0; i--) {\n        if(PositionGetSymbol(i) == _Symbol && PositionGetInteger(POSITION_MAGIC) == MagicNumber) {\n            trade.PositionClose(PositionGetTicket(i));\n        }\n    }\n}\n\nint CountPositions() {\n    int count = 0;\n    for(int i = PositionsTotal() - 1; i >= 0; i--) {\n        if(PositionGetSymbol(i) == _Symbol && PositionGetInteger(POSITION_MAGIC) == MagicNumber)\n            count++;\n    }\n    return count;\n}\n\ndouble CalculateLotSize(double slDistance) {\n    double balance = AccountInfoDouble(ACCOUNT_BALANCE);\n    double riskAmount = balance * RiskPercent / 100.0;\n    double tickValue = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_VALUE);\n    double tickSize = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_SIZE);\n    if(tickValue == 0 || tickSize == 0 || slDistance == 0) return 0.01;\n    double lots = riskAmount / (slDistance / tickSize * tickValue);\n    lots = MathMax(lots, SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MIN));\n    lots = MathMin(lots, SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MAX));\n    return NormalizeDouble(lots, 2);\n}\n",
    strategySnapshot: {
      name: 'London Breakout',
      market: 'XAUUSD',
      entry_rules: [
        'Calculate Asian session high/low range (4 hours before London)',
        'Buy when price breaks above range high during London hours (8-10)',
        'Sell when price breaks below range low during London hours',
      ],
      exit_rules: [
        'SL = range height × 1.0',
        'TP = range height × 2.0',
        'Close all positions at hour 20 (end of NY session)',
      ],
      risk_logic: '1% risk per trade. Max 2 concurrent positions.',
    },
    backtestResults: {
      sharpe: 0.45, max_drawdown: 3.2, win_rate: 52.0, total_return: 5.86,
      profit_factor: 1.04, total_trades: 25, net_profit: 585.65,
      equity_curve: [
        { date: '2023-01-01', equity: 10000 }, { date: '2023-04-01', equity: 10120 },
        { date: '2023-07-01', equity: 10050 }, { date: '2023-10-01', equity: 10280 },
        { date: '2024-01-01', equity: 10200 }, { date: '2024-04-01', equity: 10380 },
        { date: '2024-07-01', equity: 10320 }, { date: '2024-10-01', equity: 10500 },
        { date: '2025-01-01', equity: 10586 },
      ],
    },
  },
  {
    id: 'trend-rider',
    name: 'Trend Rider',
    prompt: 'Build a XAUUSD trend following strategy on H1. Use EMA(10) and EMA(30) crossover with EMA(50) as trend filter — only buy when price is above EMA(50) and trend is rising. Add trailing stop. SL = 1.5×ATR, TP = 2×ATR. Max 2 positions, 1% risk per trade.',
    description: 'Multi-timeframe trend following with EMA(10)/EMA(30) crossover filtered by EMA(50) trend direction. Includes trailing stop.',
    market: 'XAUUSD',
    timeframe: 'H1',
    mql5Code: "//+------------------------------------------------------------------+\n//|                                           Trend_Rider.mq5         |\n//|                                           Generated by SIGX       |\n//+------------------------------------------------------------------+\n#property copyright \"SIGX\"\n#property version   \"1.00\"\n#include <Trade/Trade.mqh>\n\ninput double RiskPercent   = 1.0;\ninput int    MagicNumber   = 200003;\ninput int    EMA_Fast      = 10;\ninput int    EMA_Slow      = 30;\ninput int    EMA_Trend     = 50;    // Shorter trend filter for more signals\ninput int    ATR_Period    = 14;\ninput double SL_Mult       = 1.5;\ninput double TP_Mult       = 2.0;   // Tighter TP (was 3.0)\ninput int    MaxPositions  = 2;\ninput int    TrailStart    = 100;   // Start trailing after X points profit\n\nCTrade trade;\nint hEmaFast, hEmaSlow, hEmaTrend, hATR;\n\nint OnInit() {\n    trade.SetExpertMagicNumber(MagicNumber);\n    hEmaFast  = iMA(_Symbol, PERIOD_H1, EMA_Fast, 0, MODE_EMA, PRICE_CLOSE);\n    hEmaSlow  = iMA(_Symbol, PERIOD_H1, EMA_Slow, 0, MODE_EMA, PRICE_CLOSE);\n    hEmaTrend = iMA(_Symbol, PERIOD_H1, EMA_Trend, 0, MODE_EMA, PRICE_CLOSE);\n    hATR      = iATR(_Symbol, PERIOD_H1, ATR_Period);\n    if(hEmaFast == INVALID_HANDLE || hEmaSlow == INVALID_HANDLE ||\n       hEmaTrend == INVALID_HANDLE || hATR == INVALID_HANDLE)\n        return INIT_FAILED;\n    return INIT_SUCCEEDED;\n}\n\nvoid OnDeinit(const int reason) {\n    IndicatorRelease(hEmaFast);\n    IndicatorRelease(hEmaSlow);\n    IndicatorRelease(hEmaTrend);\n    IndicatorRelease(hATR);\n}\n\nvoid OnTick() {\n    // Trailing stop management on every tick\n    ManageTrailingStop();\n\n    static datetime lastBar = 0;\n    datetime currentBar = iTime(_Symbol, PERIOD_H1, 0);\n    if(currentBar == lastBar) return;\n    lastBar = currentBar;\n\n    double emaF[], emaS[], emaT[], atr[];\n    ArraySetAsSeries(emaF, true);\n    ArraySetAsSeries(emaS, true);\n    ArraySetAsSeries(emaT, true);\n    ArraySetAsSeries(atr, true);\n    CopyBuffer(hEmaFast, 0, 0, 3, emaF);\n    CopyBuffer(hEmaSlow, 0, 0, 3, emaS);\n    CopyBuffer(hEmaTrend, 0, 0, 3, emaT);\n    CopyBuffer(hATR, 0, 0, 3, atr);\n\n    if(CountPositions() >= MaxPositions) return;\n\n    double ask = SymbolInfoDouble(_Symbol, SYMBOL_ASK);\n    double bid = SymbolInfoDouble(_Symbol, SYMBOL_BID);\n    double sl = atr[1] * SL_Mult;\n    double tp = atr[1] * TP_Mult;\n    double lots = CalculateLotSize(sl);\n    if(lots < 0.01) lots = 0.01;\n\n    double close1 = iClose(_Symbol, PERIOD_H1, 1);\n\n    // BUY: Fast crosses above Slow + Price above Trend EMA + Trend rising\n    if(emaF[2] < emaS[2] && emaF[1] > emaS[1] && close1 > emaT[1] && emaT[1] > emaT[2]) {\n        trade.Buy(lots, _Symbol, ask, ask - sl, ask + tp);\n    }\n\n    // SELL: Fast crosses below Slow + Price below Trend EMA + Trend falling\n    if(emaF[2] > emaS[2] && emaF[1] < emaS[1] && close1 < emaT[1] && emaT[1] < emaT[2]) {\n        trade.Sell(lots, _Symbol, bid, bid + sl, bid - tp);\n    }\n}\n\nvoid ManageTrailingStop() {\n    double point = SymbolInfoDouble(_Symbol, SYMBOL_POINT);\n    double trailDist = TrailStart * point;\n\n    for(int i = PositionsTotal() - 1; i >= 0; i--) {\n        if(PositionGetSymbol(i) != _Symbol) continue;\n        if(PositionGetInteger(POSITION_MAGIC) != MagicNumber) continue;\n\n        ulong ticket = PositionGetTicket(i);\n        double openPrice = PositionGetDouble(POSITION_PRICE_OPEN);\n        double currentSL = PositionGetDouble(POSITION_SL);\n        double currentTP = PositionGetDouble(POSITION_TP);\n        long type = PositionGetInteger(POSITION_TYPE);\n\n        if(type == POSITION_TYPE_BUY) {\n            double bid = SymbolInfoDouble(_Symbol, SYMBOL_BID);\n            double profit = bid - openPrice;\n            if(profit > trailDist) {\n                double newSL = bid - trailDist;\n                if(newSL > currentSL) {\n                    trade.PositionModify(ticket, newSL, currentTP);\n                }\n            }\n        } else {\n            double ask = SymbolInfoDouble(_Symbol, SYMBOL_ASK);\n            double profit = openPrice - ask;\n            if(profit > trailDist) {\n                double newSL = ask + trailDist;\n                if(newSL < currentSL || currentSL == 0) {\n                    trade.PositionModify(ticket, newSL, currentTP);\n                }\n            }\n        }\n    }\n}\n\nint CountPositions() {\n    int count = 0;\n    for(int i = PositionsTotal() - 1; i >= 0; i--) {\n        if(PositionGetSymbol(i) == _Symbol && PositionGetInteger(POSITION_MAGIC) == MagicNumber)\n            count++;\n    }\n    return count;\n}\n\ndouble CalculateLotSize(double slDistance) {\n    double balance = AccountInfoDouble(ACCOUNT_BALANCE);\n    double riskAmount = balance * RiskPercent / 100.0;\n    double tickValue = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_VALUE);\n    double tickSize = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_SIZE);\n    if(tickValue == 0 || tickSize == 0 || slDistance == 0) return 0.01;\n    double lots = riskAmount / (slDistance / tickSize * tickValue);\n    lots = MathMax(lots, SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MIN));\n    lots = MathMin(lots, SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MAX));\n    return NormalizeDouble(lots, 2);\n}\n",
    strategySnapshot: {
      name: 'Trend Rider',
      market: 'XAUUSD',
      entry_rules: [
        'EMA(10) crosses above EMA(30) + Price above EMA(50) + Trend rising → Buy',
        'EMA(10) crosses below EMA(30) + Price below EMA(50) + Trend falling → Sell',
      ],
      exit_rules: [
        'SL = 1.5 × ATR(14)',
        'TP = 2.0 × ATR(14)',
        'Trailing stop activates after 100 points profit',
      ],
      risk_logic: '1% risk per trade. Max 2 concurrent positions. ATR-based dynamic stops with trailing.',
    },
    backtestResults: {
      sharpe: 1.10, max_drawdown: 8.5, win_rate: 48.6, total_return: 52.08,
      profit_factor: 1.10, total_trades: 364, net_profit: 5208.02,
      equity_curve: [
        { date: '2023-01-01', equity: 10000 }, { date: '2023-04-01', equity: 10800 },
        { date: '2023-07-01', equity: 11200 }, { date: '2023-10-01', equity: 10900 },
        { date: '2024-01-01', equity: 11800 }, { date: '2024-04-01', equity: 12500 },
        { date: '2024-07-01', equity: 13100 }, { date: '2024-10-01', equity: 14200 },
        { date: '2025-01-01', equity: 15208 },
      ],
    },
  },
  {
    id: 'mean-reversion',
    name: 'Mean Reversion',
    prompt: 'Build a XAUUSD mean reversion strategy on H1. Use Bollinger Bands(20, 2.0) with RSI(14) confirmation. Buy when price bounces off lower band with RSI < 35. Sell when price drops from upper band with RSI > 65. SL and TP = 1.5×ATR. Max 2 positions, 1% risk per trade.',
    description: 'Bollinger Band bounce strategy with RSI confirmation. Enters on band touches and targets mean reversion.',
    market: 'XAUUSD',
    timeframe: 'H1',
    mql5Code: "//+------------------------------------------------------------------+\n//|                                       Mean_Reversion.mq5          |\n//|                                       Generated by SIGX           |\n//+------------------------------------------------------------------+\n#property copyright \"SIGX\"\n#property version   \"1.00\"\n#include <Trade/Trade.mqh>\n\ninput double RiskPercent   = 1.0;\ninput int    MagicNumber   = 200004;\ninput int    BB_Period     = 20;\ninput double BB_Dev        = 2.0;\ninput int    RSI_Period    = 14;\ninput double RSI_OB        = 65;    // Looser thresholds for more trades\ninput double RSI_OS        = 35;\ninput int    ATR_Period    = 14;\ninput double SL_Mult       = 1.5;\ninput double TP_Mult       = 1.5;   // Mean reversion: moderate TP\ninput int    MaxPositions  = 2;\n\nCTrade trade;\nint hBB, hRSI, hATR;\n\nint OnInit() {\n    trade.SetExpertMagicNumber(MagicNumber);\n    hBB  = iBands(_Symbol, PERIOD_H1, BB_Period, 0, BB_Dev, PRICE_CLOSE);\n    hRSI = iRSI(_Symbol, PERIOD_H1, RSI_Period, PRICE_CLOSE);\n    hATR = iATR(_Symbol, PERIOD_H1, ATR_Period);\n    if(hBB == INVALID_HANDLE || hRSI == INVALID_HANDLE || hATR == INVALID_HANDLE)\n        return INIT_FAILED;\n    return INIT_SUCCEEDED;\n}\n\nvoid OnDeinit(const int reason) {\n    IndicatorRelease(hBB);\n    IndicatorRelease(hRSI);\n    IndicatorRelease(hATR);\n}\n\nvoid OnTick() {\n    static datetime lastBar = 0;\n    datetime currentBar = iTime(_Symbol, PERIOD_H1, 0);\n    if(currentBar == lastBar) return;\n    lastBar = currentBar;\n\n    double bbUpper[], bbLower[], bbMiddle[], rsi[], atr[];\n    ArraySetAsSeries(bbUpper, true);\n    ArraySetAsSeries(bbLower, true);\n    ArraySetAsSeries(bbMiddle, true);\n    ArraySetAsSeries(rsi, true);\n    ArraySetAsSeries(atr, true);\n    CopyBuffer(hBB, 1, 0, 3, bbUpper);   // Upper band\n    CopyBuffer(hBB, 2, 0, 3, bbLower);   // Lower band\n    CopyBuffer(hBB, 0, 0, 3, bbMiddle);  // Middle band\n    CopyBuffer(hRSI, 0, 0, 3, rsi);\n    CopyBuffer(hATR, 0, 0, 3, atr);\n\n    if(CountPositions() >= MaxPositions) return;\n\n    double close1 = iClose(_Symbol, PERIOD_H1, 1);\n    double close2 = iClose(_Symbol, PERIOD_H1, 2);\n    double ask = SymbolInfoDouble(_Symbol, SYMBOL_ASK);\n    double bid = SymbolInfoDouble(_Symbol, SYMBOL_BID);\n    double sl = atr[1] * SL_Mult;\n    double tp = atr[1] * TP_Mult;\n    double lots = CalculateLotSize(sl);\n    if(lots < 0.01) lots = 0.01;\n\n    // BUY: Price was below lower BB and bounced back up + RSI oversold\n    if(close2 <= bbLower[2] && close1 > bbLower[1] && rsi[1] < RSI_OS) {\n        trade.Buy(lots, _Symbol, ask, ask - sl, ask + tp);\n    }\n\n    // SELL: Price was above upper BB and dropped back down + RSI overbought\n    if(close2 >= bbUpper[2] && close1 < bbUpper[1] && rsi[1] > RSI_OB) {\n        trade.Sell(lots, _Symbol, bid, bid + sl, bid - tp);\n    }\n}\n\nint CountPositions() {\n    int count = 0;\n    for(int i = PositionsTotal() - 1; i >= 0; i--) {\n        if(PositionGetSymbol(i) == _Symbol && PositionGetInteger(POSITION_MAGIC) == MagicNumber)\n            count++;\n    }\n    return count;\n}\n\ndouble CalculateLotSize(double slDistance) {\n    double balance = AccountInfoDouble(ACCOUNT_BALANCE);\n    double riskAmount = balance * RiskPercent / 100.0;\n    double tickValue = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_VALUE);\n    double tickSize = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_SIZE);\n    if(tickValue == 0 || tickSize == 0 || slDistance == 0) return 0.01;\n    double lots = riskAmount / (slDistance / tickSize * tickValue);\n    lots = MathMax(lots, SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MIN));\n    lots = MathMin(lots, SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MAX));\n    return NormalizeDouble(lots, 2);\n}\n",
    strategySnapshot: {
      name: 'Mean Reversion',
      market: 'XAUUSD',
      entry_rules: [
        'Price bounces off lower BB(20,2) + RSI(14) < 35 → Buy',
        'Price bounces off upper BB(20,2) + RSI(14) > 65 → Sell',
      ],
      exit_rules: [
        'SL = 1.5 × ATR(14)',
        'TP = 1.5 × ATR(14)',
      ],
      risk_logic: '1% risk per trade. Max 2 concurrent positions.',
    },
    backtestResults: {
      sharpe: 0.55, max_drawdown: 6.8, win_rate: 50.2, total_return: 22.96,
      profit_factor: 1.02, total_trades: 259, net_profit: 2296.28,
      equity_curve: [
        { date: '2023-01-01', equity: 10000 }, { date: '2023-04-01', equity: 10350 },
        { date: '2023-07-01', equity: 10150 }, { date: '2023-10-01', equity: 10600 },
        { date: '2024-01-01', equity: 10450 }, { date: '2024-04-01', equity: 10900 },
        { date: '2024-07-01', equity: 11200 }, { date: '2024-10-01', equity: 11800 },
        { date: '2025-01-01', equity: 12296 },
      ],
    },
  },
]

export function findClientTemplate(text: string): ClientTemplate | null {
  const lower = text.toLowerCase()
  for (const t of CLIENT_TEMPLATES) {
    if (lower.includes(t.name.toLowerCase())) return t
  }
  return null
}
