//+------------------------------------------------------------------+
//|                                         London_Breakout.mq5       |
//|                                         Generated by SIGX         |
//+------------------------------------------------------------------+
#property copyright "SIGX"
#property version   "1.00"
#include <Trade/Trade.mqh>

input double RiskPercent    = 1.0;
input int    MagicNumber    = 200001;
input int    LondonStartHour = 8;    // London session start (server time)
input int    LondonEndHour   = 10;   // Breakout window end
input int    CloseHour       = 20;   // Close all trades
input int    RangeLookback   = 4;    // Hours before London to measure range
input double SL_Multiplier   = 1.0;  // SL = range height * multiplier
input double TP_Multiplier   = 2.0;  // TP = range height * multiplier
input int    MaxPositions    = 2;

CTrade trade;
int hATR;

int OnInit() {
    trade.SetExpertMagicNumber(MagicNumber);
    hATR = iATR(_Symbol, PERIOD_H1, 14);
    if(hATR == INVALID_HANDLE) return INIT_FAILED;
    return INIT_SUCCEEDED;
}

void OnDeinit(const int reason) {
    IndicatorRelease(hATR);
}

void OnTick() {
    MqlDateTime dt;
    TimeToStruct(TimeCurrent(), dt);

    // Close all positions at CloseHour
    if(dt.hour >= CloseHour) {
        CloseAllPositions();
        return;
    }

    // Only trade during London breakout window
    if(dt.hour < LondonStartHour || dt.hour >= LondonEndHour) return;

    static datetime lastBar = 0;
    datetime currentBar = iTime(_Symbol, PERIOD_H1, 0);
    if(currentBar == lastBar) return;
    lastBar = currentBar;

    if(CountPositions() >= MaxPositions) return;

    // Calculate Asian session range (before London)
    double rangeHigh = -999999, rangeLow = 999999;
    for(int i = 1; i <= RangeLookback; i++) {
        double h = iHigh(_Symbol, PERIOD_H1, i);
        double l = iLow(_Symbol, PERIOD_H1, i);
        if(h > rangeHigh) rangeHigh = h;
        if(l < rangeLow)  rangeLow = l;
    }

    double rangeSize = rangeHigh - rangeLow;
    if(rangeSize < _Point * 10) return; // Too narrow

    double ask = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
    double bid = SymbolInfoDouble(_Symbol, SYMBOL_BID);
    double sl = rangeSize * SL_Multiplier;
    double tp = rangeSize * TP_Multiplier;
    double lots = CalculateLotSize(sl);

    // Breakout above range
    if(ask > rangeHigh) {
        trade.Buy(lots, _Symbol, ask, ask - sl, ask + tp);
    }
    // Breakout below range
    if(bid < rangeLow) {
        trade.Sell(lots, _Symbol, bid, bid + sl, bid - tp);
    }
}

void CloseAllPositions() {
    for(int i = PositionsTotal() - 1; i >= 0; i--) {
        if(PositionGetSymbol(i) == _Symbol && PositionGetInteger(POSITION_MAGIC) == MagicNumber) {
            trade.PositionClose(PositionGetTicket(i));
        }
    }
}

int CountPositions() {
    int count = 0;
    for(int i = PositionsTotal() - 1; i >= 0; i--) {
        if(PositionGetSymbol(i) == _Symbol && PositionGetInteger(POSITION_MAGIC) == MagicNumber)
            count++;
    }
    return count;
}

double CalculateLotSize(double slDistance) {
    double balance = AccountInfoDouble(ACCOUNT_BALANCE);
    double riskAmount = balance * RiskPercent / 100.0;
    double tickValue = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_VALUE);
    double tickSize = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_SIZE);
    if(tickValue == 0 || tickSize == 0 || slDistance == 0) return 0.01;
    double lots = riskAmount / (slDistance / tickSize * tickValue);
    lots = MathMax(lots, SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MIN));
    lots = MathMin(lots, SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MAX));
    return NormalizeDouble(lots, 2);
}
