//+------------------------------------------------------------------+
//|                                       Mean_Reversion.mq5          |
//|                                       Generated by SIGX           |
//+------------------------------------------------------------------+
#property copyright "SIGX"
#property version   "1.00"
#include <Trade/Trade.mqh>

input double RiskPercent   = 1.0;
input int    MagicNumber   = 200004;
input int    BB_Period     = 20;
input double BB_Dev        = 2.0;
input int    RSI_Period    = 14;
input double RSI_OB        = 65;    // Looser thresholds for more trades
input double RSI_OS        = 35;
input int    ATR_Period    = 14;
input double SL_Mult       = 1.5;
input double TP_Mult       = 1.5;   // Mean reversion: moderate TP
input int    MaxPositions  = 2;

CTrade trade;
int hBB, hRSI, hATR;

int OnInit() {
    trade.SetExpertMagicNumber(MagicNumber);
    hBB  = iBands(_Symbol, PERIOD_H1, BB_Period, 0, BB_Dev, PRICE_CLOSE);
    hRSI = iRSI(_Symbol, PERIOD_H1, RSI_Period, PRICE_CLOSE);
    hATR = iATR(_Symbol, PERIOD_H1, ATR_Period);
    if(hBB == INVALID_HANDLE || hRSI == INVALID_HANDLE || hATR == INVALID_HANDLE)
        return INIT_FAILED;
    return INIT_SUCCEEDED;
}

void OnDeinit(const int reason) {
    IndicatorRelease(hBB);
    IndicatorRelease(hRSI);
    IndicatorRelease(hATR);
}

void OnTick() {
    static datetime lastBar = 0;
    datetime currentBar = iTime(_Symbol, PERIOD_H1, 0);
    if(currentBar == lastBar) return;
    lastBar = currentBar;

    double bbUpper[], bbLower[], bbMiddle[], rsi[], atr[];
    ArraySetAsSeries(bbUpper, true);
    ArraySetAsSeries(bbLower, true);
    ArraySetAsSeries(bbMiddle, true);
    ArraySetAsSeries(rsi, true);
    ArraySetAsSeries(atr, true);
    CopyBuffer(hBB, 1, 0, 3, bbUpper);   // Upper band
    CopyBuffer(hBB, 2, 0, 3, bbLower);   // Lower band
    CopyBuffer(hBB, 0, 0, 3, bbMiddle);  // Middle band
    CopyBuffer(hRSI, 0, 0, 3, rsi);
    CopyBuffer(hATR, 0, 0, 3, atr);

    if(CountPositions() >= MaxPositions) return;

    double close1 = iClose(_Symbol, PERIOD_H1, 1);
    double close2 = iClose(_Symbol, PERIOD_H1, 2);
    double ask = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
    double bid = SymbolInfoDouble(_Symbol, SYMBOL_BID);
    double sl = atr[1] * SL_Mult;
    double tp = atr[1] * TP_Mult;
    double lots = CalculateLotSize(sl);
    if(lots < 0.01) lots = 0.01;

    // BUY: Price was below lower BB and bounced back up + RSI oversold
    if(close2 <= bbLower[2] && close1 > bbLower[1] && rsi[1] < RSI_OS) {
        trade.Buy(lots, _Symbol, ask, ask - sl, ask + tp);
    }

    // SELL: Price was above upper BB and dropped back down + RSI overbought
    if(close2 >= bbUpper[2] && close1 < bbUpper[1] && rsi[1] > RSI_OB) {
        trade.Sell(lots, _Symbol, bid, bid + sl, bid - tp);
    }
}

int CountPositions() {
    int count = 0;
    for(int i = PositionsTotal() - 1; i >= 0; i--) {
        if(PositionGetSymbol(i) == _Symbol && PositionGetInteger(POSITION_MAGIC) == MagicNumber)
            count++;
    }
    return count;
}

double CalculateLotSize(double slDistance) {
    double balance = AccountInfoDouble(ACCOUNT_BALANCE);
    double riskAmount = balance * RiskPercent / 100.0;
    double tickValue = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_VALUE);
    double tickSize = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_SIZE);
    if(tickValue == 0 || tickSize == 0 || slDistance == 0) return 0.01;
    double lots = riskAmount / (slDistance / tickSize * tickValue);
    lots = MathMax(lots, SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MIN));
    lots = MathMin(lots, SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MAX));
    return NormalizeDouble(lots, 2);
}
