//+------------------------------------------------------------------+
//|                                       Momentum_Alpha.mq5          |
//|                                       Generated by SIGX           |
//+------------------------------------------------------------------+
#property copyright "SIGX"
#property version   "1.00"
#include <Trade/Trade.mqh>

input double RiskPercent   = 1.0;
input int    MagicNumber   = 200005;
input int    MACD_Fast     = 12;
input int    MACD_Slow     = 26;
input int    MACD_Signal   = 9;
input int    EMA_Period    = 50;    // Trend filter
input int    ATR_Period    = 14;
input double SL_Mult       = 1.5;
input double TP_Mult       = 2.5;
input int    MaxPositions  = 2;

CTrade trade;
int hMACD, hEMA, hATR;

int OnInit() {
    trade.SetExpertMagicNumber(MagicNumber);
    hMACD = iMACD(_Symbol, PERIOD_H1, MACD_Fast, MACD_Slow, MACD_Signal, PRICE_CLOSE);
    hEMA  = iMA(_Symbol, PERIOD_H1, EMA_Period, 0, MODE_EMA, PRICE_CLOSE);
    hATR  = iATR(_Symbol, PERIOD_H1, ATR_Period);
    if(hMACD == INVALID_HANDLE || hEMA == INVALID_HANDLE || hATR == INVALID_HANDLE)
        return INIT_FAILED;
    return INIT_SUCCEEDED;
}

void OnDeinit(const int reason) {
    IndicatorRelease(hMACD);
    IndicatorRelease(hEMA);
    IndicatorRelease(hATR);
}

void OnTick() {
    static datetime lastBar = 0;
    datetime currentBar = iTime(_Symbol, PERIOD_H1, 0);
    if(currentBar == lastBar) return;
    lastBar = currentBar;

    double macdMain[], macdSignal[], ema[], atr[];
    ArraySetAsSeries(macdMain, true);
    ArraySetAsSeries(macdSignal, true);
    ArraySetAsSeries(ema, true);
    ArraySetAsSeries(atr, true);
    CopyBuffer(hMACD, 0, 0, 3, macdMain);     // MACD main line
    CopyBuffer(hMACD, 1, 0, 3, macdSignal);   // MACD signal line
    CopyBuffer(hEMA, 0, 0, 3, ema);
    CopyBuffer(hATR, 0, 0, 3, atr);

    if(CountPositions() >= MaxPositions) return;

    double close1 = iClose(_Symbol, PERIOD_H1, 1);
    double ask = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
    double bid = SymbolInfoDouble(_Symbol, SYMBOL_BID);
    double sl = atr[1] * SL_Mult;
    double tp = atr[1] * TP_Mult;
    double lots = CalculateLotSize(sl);
    if(lots < 0.01) lots = 0.01;

    // BUY: MACD crosses above signal + Price above EMA (bullish momentum)
    if(macdMain[2] < macdSignal[2] && macdMain[1] > macdSignal[1] && close1 > ema[1]) {
        trade.Buy(lots, _Symbol, ask, ask - sl, ask + tp);
    }

    // SELL: MACD crosses below signal + Price below EMA (bearish momentum)
    if(macdMain[2] > macdSignal[2] && macdMain[1] < macdSignal[1] && close1 < ema[1]) {
        trade.Sell(lots, _Symbol, bid, bid + sl, bid - tp);
    }
}

int CountPositions() {
    int count = 0;
    for(int i = PositionsTotal() - 1; i >= 0; i--) {
        if(PositionGetSymbol(i) == _Symbol && PositionGetInteger(POSITION_MAGIC) == MagicNumber)
            count++;
    }
    return count;
}

double CalculateLotSize(double slDistance) {
    double balance = AccountInfoDouble(ACCOUNT_BALANCE);
    double riskAmount = balance * RiskPercent / 100.0;
    double tickValue = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_VALUE);
    double tickSize = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_SIZE);
    if(tickValue == 0 || tickSize == 0 || slDistance == 0) return 0.01;
    double lots = riskAmount / (slDistance / tickSize * tickValue);
    lots = MathMax(lots, SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MIN));
    lots = MathMin(lots, SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MAX));
    return NormalizeDouble(lots, 2);
}
