//+------------------------------------------------------------------+
//|                                            Scalper_Pro.mq5        |
//|                                            Generated by SIGX      |
//+------------------------------------------------------------------+
#property copyright "SIGX"
#property version   "1.00"
#include <Trade/Trade.mqh>

input double RiskPercent   = 0.5;
input int    MagicNumber   = 200002;
input int    RSI_Period    = 2;      // Very short RSI for mean-reversion scalping
input double RSI_Buy       = 15;     // Oversold bounce
input double RSI_Sell      = 85;     // Overbought rejection
input int    ATR_Period    = 14;
input double SL_Mult       = 1.5;
input double TP_Mult       = 1.5;    // Quick scalp exit
input int    MaxPositions  = 1;

CTrade trade;
int hRSI, hATR, hEMA;

int OnInit() {
    trade.SetExpertMagicNumber(MagicNumber);
    hRSI = iRSI(_Symbol, PERIOD_H1, RSI_Period, PRICE_CLOSE);
    hATR = iATR(_Symbol, PERIOD_H1, ATR_Period);
    hEMA = iMA(_Symbol, PERIOD_H1, 50, 0, MODE_EMA, PRICE_CLOSE);
    if(hRSI == INVALID_HANDLE || hATR == INVALID_HANDLE || hEMA == INVALID_HANDLE)
        return INIT_FAILED;
    return INIT_SUCCEEDED;
}

void OnDeinit(const int reason) {
    IndicatorRelease(hRSI);
    IndicatorRelease(hATR);
    IndicatorRelease(hEMA);
}

void OnTick() {
    static datetime lastBar = 0;
    datetime currentBar = iTime(_Symbol, PERIOD_H1, 0);
    if(currentBar == lastBar) return;
    lastBar = currentBar;

    double rsi[], atr[], ema[];
    ArraySetAsSeries(rsi, true);
    ArraySetAsSeries(atr, true);
    ArraySetAsSeries(ema, true);
    CopyBuffer(hRSI, 0, 0, 3, rsi);
    CopyBuffer(hATR, 0, 0, 3, atr);
    CopyBuffer(hEMA, 0, 0, 3, ema);

    if(CountPositions() >= MaxPositions) return;

    double close1 = iClose(_Symbol, PERIOD_H1, 1);
    double ask = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
    double bid = SymbolInfoDouble(_Symbol, SYMBOL_BID);
    double sl = atr[1] * SL_Mult;
    double tp = atr[1] * TP_Mult;
    double lots = CalculateLotSize(sl);
    if(lots < 0.01) lots = 0.01;

    // BUY: RSI(2) extreme oversold + price above H1 EMA50 (buy dips in uptrend)
    if(rsi[1] < RSI_Buy && close1 > ema[1]) {
        trade.Buy(lots, _Symbol, ask, ask - sl, ask + tp);
    }

    // SELL: RSI(2) extreme overbought + price below H1 EMA50 (sell rallies in downtrend)
    if(rsi[1] > RSI_Sell && close1 < ema[1]) {
        trade.Sell(lots, _Symbol, bid, bid + sl, bid - tp);
    }
}

int CountPositions() {
    int count = 0;
    for(int i = PositionsTotal() - 1; i >= 0; i--) {
        if(PositionGetSymbol(i) == _Symbol && PositionGetInteger(POSITION_MAGIC) == MagicNumber)
            count++;
    }
    return count;
}

double CalculateLotSize(double slDistance) {
    double balance = AccountInfoDouble(ACCOUNT_BALANCE);
    double riskAmount = balance * RiskPercent / 100.0;
    double tickValue = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_VALUE);
    double tickSize = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_SIZE);
    if(tickValue == 0 || tickSize == 0 || slDistance == 0) return 0.01;
    double lots = riskAmount / (slDistance / tickSize * tickValue);
    lots = MathMax(lots, SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MIN));
    lots = MathMin(lots, SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MAX));
    return NormalizeDouble(lots, 2);
}
