//+------------------------------------------------------------------+
//|                                            Scalper_Pro.mq5        |
//|                                            Generated by SIGX      |
//+------------------------------------------------------------------+
#property copyright "SIGX"
#property version   "1.00"
#include <Trade/Trade.mqh>

input double RiskPercent   = 0.5;
input int    MagicNumber   = 200002;
input int    EMA_Fast      = 8;
input int    EMA_Slow      = 21;
input int    RSI_Period    = 7;
input double RSI_OB        = 70;
input double RSI_OS        = 30;
input double SL_Points     = 150;    // SL in points
input double TP_Points     = 100;    // TP in points (scalping: tight TP)
input int    MaxPositions  = 3;

CTrade trade;
int hEmaFast, hEmaSlow, hRSI;

int OnInit() {
    trade.SetExpertMagicNumber(MagicNumber);
    hEmaFast = iMA(_Symbol, PERIOD_M5, EMA_Fast, 0, MODE_EMA, PRICE_CLOSE);
    hEmaSlow = iMA(_Symbol, PERIOD_M5, EMA_Slow, 0, MODE_EMA, PRICE_CLOSE);
    hRSI = iRSI(_Symbol, PERIOD_M5, RSI_Period, PRICE_CLOSE);
    if(hEmaFast == INVALID_HANDLE || hEmaSlow == INVALID_HANDLE || hRSI == INVALID_HANDLE)
        return INIT_FAILED;
    return INIT_SUCCEEDED;
}

void OnDeinit(const int reason) {
    IndicatorRelease(hEmaFast);
    IndicatorRelease(hEmaSlow);
    IndicatorRelease(hRSI);
}

void OnTick() {
    static datetime lastBar = 0;
    datetime currentBar = iTime(_Symbol, PERIOD_M5, 0);
    if(currentBar == lastBar) return;
    lastBar = currentBar;

    double emaF[], emaS[], rsi[];
    ArraySetAsSeries(emaF, true);
    ArraySetAsSeries(emaS, true);
    ArraySetAsSeries(rsi, true);
    CopyBuffer(hEmaFast, 0, 0, 3, emaF);
    CopyBuffer(hEmaSlow, 0, 0, 3, emaS);
    CopyBuffer(hRSI, 0, 0, 3, rsi);

    if(CountPositions() >= MaxPositions) return;

    double ask = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
    double bid = SymbolInfoDouble(_Symbol, SYMBOL_BID);
    double point = SymbolInfoDouble(_Symbol, SYMBOL_POINT);
    double lots = CalculateLotSize(SL_Points * point);
    if(lots < 0.01) lots = 0.01;

    // BUY: Fast EMA crosses above Slow EMA + RSI not overbought
    if(emaF[2] < emaS[2] && emaF[1] > emaS[1] && rsi[1] < RSI_OB) {
        trade.Buy(lots, _Symbol, ask, ask - SL_Points * point, ask + TP_Points * point);
    }

    // SELL: Fast EMA crosses below Slow EMA + RSI not oversold
    if(emaF[2] > emaS[2] && emaF[1] < emaS[1] && rsi[1] > RSI_OS) {
        trade.Sell(lots, _Symbol, bid, bid + SL_Points * point, bid - TP_Points * point);
    }
}

int CountPositions() {
    int count = 0;
    for(int i = PositionsTotal() - 1; i >= 0; i--) {
        if(PositionGetSymbol(i) == _Symbol && PositionGetInteger(POSITION_MAGIC) == MagicNumber)
            count++;
    }
    return count;
}

double CalculateLotSize(double slDistance) {
    double balance = AccountInfoDouble(ACCOUNT_BALANCE);
    double riskAmount = balance * RiskPercent / 100.0;
    double tickValue = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_VALUE);
    double tickSize = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_SIZE);
    if(tickValue == 0 || tickSize == 0 || slDistance == 0) return 0.01;
    double lots = riskAmount / (slDistance / tickSize * tickValue);
    lots = MathMax(lots, SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MIN));
    lots = MathMin(lots, SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MAX));
    return NormalizeDouble(lots, 2);
}
