//+------------------------------------------------------------------+
//|                                           Trend_Rider.mq5         |
//|                                           Generated by SIGX       |
//+------------------------------------------------------------------+
#property copyright "SIGX"
#property version   "1.00"
#include <Trade/Trade.mqh>

input double RiskPercent   = 1.0;
input int    MagicNumber   = 200003;
input int    EMA_Fast      = 10;
input int    EMA_Slow      = 30;
input int    EMA_Trend     = 100;   // Trend filter
input int    ATR_Period    = 14;
input double SL_Mult       = 1.5;
input double TP_Mult       = 3.0;   // Wide TP for trend riding
input int    MaxPositions  = 2;

CTrade trade;
int hEmaFast, hEmaSlow, hEmaTrend, hATR;

int OnInit() {
    trade.SetExpertMagicNumber(MagicNumber);
    hEmaFast  = iMA(_Symbol, PERIOD_H1, EMA_Fast, 0, MODE_EMA, PRICE_CLOSE);
    hEmaSlow  = iMA(_Symbol, PERIOD_H1, EMA_Slow, 0, MODE_EMA, PRICE_CLOSE);
    hEmaTrend = iMA(_Symbol, PERIOD_H1, EMA_Trend, 0, MODE_EMA, PRICE_CLOSE);
    hATR      = iATR(_Symbol, PERIOD_H1, ATR_Period);
    if(hEmaFast == INVALID_HANDLE || hEmaSlow == INVALID_HANDLE ||
       hEmaTrend == INVALID_HANDLE || hATR == INVALID_HANDLE)
        return INIT_FAILED;
    return INIT_SUCCEEDED;
}

void OnDeinit(const int reason) {
    IndicatorRelease(hEmaFast);
    IndicatorRelease(hEmaSlow);
    IndicatorRelease(hEmaTrend);
    IndicatorRelease(hATR);
}

void OnTick() {
    static datetime lastBar = 0;
    datetime currentBar = iTime(_Symbol, PERIOD_H1, 0);
    if(currentBar == lastBar) return;
    lastBar = currentBar;

    double emaF[], emaS[], emaT[], atr[];
    ArraySetAsSeries(emaF, true);
    ArraySetAsSeries(emaS, true);
    ArraySetAsSeries(emaT, true);
    ArraySetAsSeries(atr, true);
    CopyBuffer(hEmaFast, 0, 0, 3, emaF);
    CopyBuffer(hEmaSlow, 0, 0, 3, emaS);
    CopyBuffer(hEmaTrend, 0, 0, 3, emaT);
    CopyBuffer(hATR, 0, 0, 3, atr);

    if(CountPositions() >= MaxPositions) return;

    double ask = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
    double bid = SymbolInfoDouble(_Symbol, SYMBOL_BID);
    double sl = atr[1] * SL_Mult;
    double tp = atr[1] * TP_Mult;
    double lots = CalculateLotSize(sl);
    if(lots < 0.01) lots = 0.01;

    double close1 = iClose(_Symbol, PERIOD_H1, 1);

    // BUY: Fast crosses above Slow + Price above Trend EMA (uptrend)
    if(emaF[2] < emaS[2] && emaF[1] > emaS[1] && close1 > emaT[1]) {
        trade.Buy(lots, _Symbol, ask, ask - sl, ask + tp);
    }

    // SELL: Fast crosses below Slow + Price below Trend EMA (downtrend)
    if(emaF[2] > emaS[2] && emaF[1] < emaS[1] && close1 < emaT[1]) {
        trade.Sell(lots, _Symbol, bid, bid + sl, bid - tp);
    }
}

int CountPositions() {
    int count = 0;
    for(int i = PositionsTotal() - 1; i >= 0; i--) {
        if(PositionGetSymbol(i) == _Symbol && PositionGetInteger(POSITION_MAGIC) == MagicNumber)
            count++;
    }
    return count;
}

double CalculateLotSize(double slDistance) {
    double balance = AccountInfoDouble(ACCOUNT_BALANCE);
    double riskAmount = balance * RiskPercent / 100.0;
    double tickValue = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_VALUE);
    double tickSize = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_SIZE);
    if(tickValue == 0 || tickSize == 0 || slDistance == 0) return 0.01;
    double lots = riskAmount / (slDistance / tickSize * tickValue);
    lots = MathMax(lots, SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MIN));
    lots = MathMin(lots, SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MAX));
    return NormalizeDouble(lots, 2);
}
