import type { Metadata } from 'next'
import LegalLayout from '@/components/legal-layout'

export const metadata: Metadata = {
  title: 'Disclaimer — SIGX',
  description: 'Important disclaimers about AI-generated trading strategies and financial risk.',
}

export default function DisclaimerPage() {
  return (
    <LegalLayout title="Disclaimer" lastUpdated="March 22, 2026">
      <section>
        <h2>AI-Generated Trading Strategies</h2>
        <p>
          SIGX uses artificial intelligence to generate, backtest, and optimize trading strategies for MetaTrader 5. <strong>All strategies produced by SIGX are generated by AI and are provided for informational and educational purposes only.</strong> They do not constitute financial advice, investment recommendations, or solicitations to trade.
        </p>
        <p>
          AI-generated strategies are based on historical data and backtesting simulations. <strong>Past performance is not indicative of future results.</strong> Backtesting results are hypothetical, do not reflect actual trading, and may not account for all market conditions, slippage, spreads, commissions, or liquidity constraints.
        </p>
      </section>

      <section>
        <h2>No Financial Advice</h2>
        <p>
          SIGX is not a registered investment advisor, broker-dealer, or financial planner. Nothing on this platform should be construed as personalized financial advice. You should consult with a qualified financial professional before making any trading or investment decisions.
        </p>
      </section>

      <section>
        <h2>Trading Risk</h2>
        <p>
          Trading financial instruments, including forex, commodities, and CFDs, involves substantial risk of loss and is not suitable for all investors. You may lose more than your initial investment. Key risks include but are not limited to:
        </p>
        <ul>
          <li><strong>Market risk:</strong> Prices can move rapidly and unpredictably against your position.</li>
          <li><strong>Leverage risk:</strong> Leveraged trading amplifies both gains and losses.</li>
          <li><strong>Technology risk:</strong> Software errors, connectivity issues, or platform outages may affect trade execution.</li>
          <li><strong>AI limitations:</strong> AI models can produce flawed logic, overfitted strategies, or code that behaves differently in live markets than in backtesting.</li>
        </ul>
        <p>
          <strong>Only trade with money you can afford to lose.</strong> SIGX is not responsible for any financial losses incurred from using strategies generated on this platform.
        </p>
      </section>

      <section>
        <h2>No Guarantees</h2>
        <p>
          SIGX does not guarantee the accuracy, completeness, or profitability of any AI-generated strategy. Strategies may contain errors, produce zero trades, or result in significant losses. Backtest metrics (profit factor, Sharpe ratio, drawdown, etc.) are estimates based on historical data and should not be relied upon as predictions of future performance.
        </p>
      </section>

      <section>
        <h2>User Responsibility</h2>
        <p>
          By using SIGX, you acknowledge and agree that:
        </p>
        <ul>
          <li>You are solely responsible for any trading decisions you make.</li>
          <li>You will review and understand any strategy code before deploying it to a live trading account.</li>
          <li>You understand that AI-generated code may contain bugs or logic errors.</li>
          <li>You will test all strategies thoroughly on a demo account before risking real capital.</li>
          <li>You will not hold SIGX, its founders, employees, or affiliates liable for any trading losses.</li>
        </ul>
      </section>

      <section>
        <h2>Hypothetical Performance Disclaimer</h2>
        <p>
          Hypothetical performance results have many inherent limitations. No representation is made that any account will or is likely to achieve profits or losses similar to those shown. There are frequently sharp differences between hypothetical performance results and the actual results subsequently achieved by any particular trading program. Hypothetical trading does not involve financial risk, and no hypothetical trading record can completely account for the impact of financial risk in actual trading.
        </p>
      </section>

      <section>
        <h2>Third-Party Services</h2>
        <p>
          SIGX integrates with MetaTrader 5 and other third-party platforms. We are not affiliated with, endorsed by, or responsible for these services. Use of third-party platforms is subject to their own terms and conditions.
        </p>
      </section>

      <section>
        <h2>Changes to This Disclaimer</h2>
        <p>
          We may update this disclaimer at any time. Continued use of SIGX after changes constitutes acceptance of the updated disclaimer.
        </p>
      </section>

      <section>
        <h2>Contact</h2>
        <p>
          If you have questions about this disclaimer, contact us at <a href="mailto:legal@sigx.ai">legal@sigx.ai</a>.
        </p>
      </section>
    </LegalLayout>
  )
}
